KM Pull Request HW13
SergeiDemyanenko/PlatformaticaQA pull request #105
Opened 2020-12-08 20:16 UTC by Kristina324

2020-12-08 23:26 UTC, sergeonevdah requested changes
70-71 line delete

2020-12-08 23:26 UTC, sergeonevdah commented on src/test/java/GroupSfbaGrizzlies_Test.java
> +        System.setProperty("webdriver.chrome.driver", "c:/Project/WEBDRIVER/chromedriver.exe");
70-71 line delete

2020-12-08 23:43 UTC, Kristina324 commented on src/test/java/GroupSfbaGrizzlies_Test.java
> +        System.setProperty("webdriver.chrome.driver", "c:/Project/WEBDRIVER/chromedriver.exe");
I am done.

2020-12-09 00:55 UTC, sergeonevdah approved these changes

2020-12-09 00:55 UTC, closed without merging