Irina ka
SergeiDemyanenko/PlatformaticaQA pull request #156
Opened 2020-12-10 20:47 UTC by irina0606

2020-12-10 21:16 UTC, SergeiDemyanenko commented on debug.log
> +[1204/164817.046:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Зачем этот файл тут?

2020-12-10 21:33 UTC, irina0606 commented on debug.log
> +[1204/164817.046:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
а что это за файл, у меня ничего такого в интелиджей не отображается

2020-12-10 21:44 UTC, irina0606 commented on debug.log
> +[1204/164817.046:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
вообще не могу понять что это

2020-12-10 23:17 UTC, viktoriia1975 approved these changes

2020-12-10 23:17 UTC, viktoriia1975 commented on debug.log
> +[1204/164817.046:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Я не увидела этот файл тоже

2020-12-10 23:38 UTC, SergeiDemyanenko commented on debug.log
> +[1204/164817.046:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Надо убрать из PR, он нам не нужен

2020-12-11 00:13 UTC, Stan575 requested changes
@irina0606 please delete PlatformaticaQA/debug.log file

2020-12-11 02:53 UTC, closed without merging