As  first test brench
SergeiDemyanenko/PlatformaticaQA pull request #189
Opened 2020-12-13 01:11 UTC by AleksandrNiceFly

2020-12-13 01:13 UTC, AleksandrNiceFly commented
я не до конца уверен, что делаю правильно ,но все же оставлю коммент)если кто увидит help pls))))

2020-12-13 05:37 UTC, SergeiDemyanenko requested changes

2020-12-13 05:37 UTC, SergeiDemyanenko commented on src/test/java/old/GroupPacificQATeamTest.java
> +        WebDriver browser = new ChromeDriver();
driver получаем из метода getDriver()

2020-12-13 05:37 UTC, SergeiDemyanenko commented on src/test/java/old/GroupPacificQATeamTest.java
> +        browser.close();
Закрытие браузера реализовано в базовом классе

2020-12-14 00:16 UTC, AleksandrNiceFly commented
Do i need to create new PR ??or you can see my changes guys ? Thanks!)

2020-12-14 01:11 UTC, Stan575 commented
All changes you commit appear in this PR, you don't need to create new one
BTW it seems there is a conflict

2020-12-14 03:41 UTC, AleksandrNiceFly commented
В скором времени догоню по урокам. Разберусь как разрешать конфликты, спасибо большое!)

2020-12-15 08:52 UTC, closed without merging