Screenshots
SergeiDemyanenko/PlatformaticaQA pull request #192
Opened 2020-12-13 21:38 UTC by ke-de-ve

2020-12-13 21:45 UTC, SergeiDemyanenko requested changes

2020-12-13 21:45 UTC, SergeiDemyanenko commented on src/test/java/EntityFieldsTest.java
> +import org.testng.annotations.Ignore;
Это тут зачем?

2020-12-13 21:45 UTC, SergeiDemyanenko commented
ScreenshotTest.java - этот класс не нужен, скрин должен делаться для каждого теста автоматически

2020-12-13 21:46 UTC, SergeiDemyanenko commented
Имя файла скрина должно быть имя теста

2020-12-13 21:47 UTC, SergeiDemyanenko commented
Не используй TestUtils, создай отдкльный класс ScreenshotUtils в пакете runner

2020-12-13 22:00 UTC, ke-de-ve commented on src/test/java/EntityFieldsTest.java
> +import org.testng.annotations.Ignore;
Didn't allow tests to run, so put ignore to be able to do my testing

2020-12-13 22:00 UTC, ke-de-ve commented on src/test/java/EntityFieldsTest.java
> +import org.testng.annotations.Ignore;
it has been resolved in the main , just a leftover in my branch

2020-12-19 16:59 UTC, ke-de-ve commented
need to make 1 more change :
works on windows.  On linux need to add separator:
ERROR: while creating directory /tmp2020-12-19-16-50-18e7a0a3-a2ef-4ef6-874b-cac2bb44120e

2020-12-19 17:17 UTC, ke-de-ve commented
Changed to make single directory per execution. Every thing works on Windows and Linux. Creates directory, takes screenshots on test failures, at the end deletes directory.  Need only to add code to upload to Drive.

2020-12-23 05:54 UTC, ke-de-ve commented
Still need to change to not even try to upload if directory is empty.

2020-12-23 20:47 UTC, SergeiDemyanenko requested changes

2020-12-23 20:47 UTC, SergeiDemyanenko commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/com.google.apis/google-api-services-drive -->
Это тут не нужно

2020-12-23 20:47 UTC, SergeiDemyanenko commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/com.google.oauth-client/google-oauth-client-jetty -->
Это тут не нужно

2020-12-23 20:47 UTC, SergeiDemyanenko commented on pom.xml
> +        <!-- https://mvnrepository.com/artifact/com.google.auth/google-auth-library-oauth2-http -->
Это тут не нужно

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/EntityLoop1Test.java
> +}
Зачем были сделаны эти изменения?

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +        // on windows last char is '\', on Linux is 'p' so need to add separator
Не думаю. что это нужно объяснять

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +        if (tempPath.charAt(tempPath.length()-1) != File.separator.charAt(0)) {
File.separatorChar

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +
Зачем ты добавил это сюда?

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/BaseTest.java
> +                    screenshotDirectoryName + File.separator + tr.getInstanceName() + "." + tr.getName() + ".png");
String.format

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    public static final String baseDirectoryName = "ScreenShots";
Не используется

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    public static final String appName = "PlatfromaticaQA";
Почему public?

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +
Пустые строки между полями не нужны, только если поля не относятся к разным логическим группам

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +
Пустые строки между полями не нужны, только если поля не относятся к разным логическим группам

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +
Пустые строки между полями не нужны, только если поля не относятся к разным логическим группам

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** get list of all files and folders with all available fields */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** get list of all files and folders with requested fields */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    private static List<File> getAllFilesList(Drive drive) {
Не используется к коде

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        if (drive == null) {
Нет таких ситуаций когда эта проверка оправдана

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        if (fields == null || fields.isEmpty()) {
Нет таких ситуаций когда эта проверка оправдана

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        return result.getFiles();
Если строка 71 вернет ошибку, то тут будет NPE из-за строки 66.

Удали строку 66, в строке 71 напиши return, а в этой строке return null.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        Drive.Files.List list = null;
я так и не понял зачему тут эта строка

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +/** set of utils to work with Google Drive */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** Create folder inside of another folder. if parentID is null then create new directory in the root */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** delete file from Drive */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** Upload image file filePath to the drive in to folder with ID=folderID */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** Upload file filePath to the drive in to folder with ID=folderID */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** Login and then upload the whole directory to drive */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** Upload whole folder of imsages to Drive inside of based folder */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** Get list of files from folder by ID */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** print into system output all files in the list */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +    /** set permissions required to share files with PlatformaticaQA@gmail.com */
Либо JavaDoc, лобо удали.

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        return file.getId();
Такая же исптори как и в getAllFilesList с NPE

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        JsonFactory jsonFactory = JacksonFactory.getDefaultInstance();
Почему эта переменная тут и зачем у нее коментарий?

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        //Build service account credentials for authorizing calls to Google APIs using OAuth2.
Это тут нужно?

2020-12-23 20:47 UTC, SergeiDemyanenko commented on src/test/java/runner/DriveUtils.java
> +        // create a wrapper for using Credentials with the Google API Client Libraries for Java with Http.
Без коментария не понять?

2020-12-23 22:13 UTC, ke-de-ve commented on src/test/java/runner/DriveUtils.java
> +    /** set permissions required to share files with PlatformaticaQA@gmail.com */
this is already sorta JavaDoc

2020-12-23 22:17 UTC, ke-de-ve commented on src/test/java/runner/BaseTest.java
> +
hmm... somehow merged this along the way by mistake

2020-12-23 23:48 UTC, ke-de-ve commented on src/test/java/runner/DriveUtils.java
> +        Drive.Files.List list = null;
missed "leftover"

2020-12-24 03:59 UTC, ke-de-ve commented
bug while uploading without any errors

2020-12-28 00:42 UTC, Stan575 approved these changes

2020-12-28 13:42 UTC, sergeonevdah approved these changes

2020-12-29 17:54 UTC, merged