Testing Calendar
SergeiDemyanenko/PlatformaticaQA pull request #195
Opened 2020-12-13 22:33 UTC by SVar25

2020-12-14 04:01 UTC, SergeiDemyanenko requested changes

2020-12-14 04:01 UTC, SergeiDemyanenko commented on src/test/java/TestUtils.java
> -
Для чего эти изменения?

2020-12-14 04:01 UTC, SergeiDemyanenko commented on src/test/java/EntityCalendarTest.java
> +        final String string = new UUID((long)(Math.random() * 1000000000), (long)(Math.random()
В коде можно найти путь проще и понятней.

2020-12-14 14:55 UTC, SVar25 commented on src/test/java/TestUtils.java
> -
Класс TestUtils я не меняла. Он в таком виде запушился из github. Я подумала, что что то поменялось в общей main ветке. Поэтому я начала городить new UUID в классе EntityCalendarTest.

2020-12-14 14:55 UTC, SVar25 commented on src/test/java/EntityCalendarTest.java
> +        final String string = new UUID((long)(Math.random() * 1000000000), (long)(Math.random()
Сережа, подскажи, пожалуйста,  как сделать проще? Я могу перенести расчет new UUID в TestUtils или ты что то другое имел в виду? Спасибо

2020-12-14 20:34 UTC, SergeiDemyanenko commented on src/test/java/EntityCalendarTest.java
> +        final String string = new UUID((long)(Math.random() * 1000000000), (long)(Math.random()
UUID.randomUUID().toString()

2020-12-15 00:18 UTC, SVar25 commented
Сережа, можешь глянуть #209. Я исправила UUID.randomUUID().toString().
https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/209
Спасибо

On Mon, Dec 14, 2020, 2:34 PM SergeiDemyanenko <notifications@github.com>
wrote:

> *@SergeiDemyanenko* commented on this pull request.
> ------------------------------
>
> In src/test/java/EntityCalendarTest.java
> <https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/195#discussion_r542752416>
> :
>
> > +public class EntityCalendarTest extends BaseTest {
> +
> +    @Test
> +    public void newCalendar() throws InterruptedException {
> +
> +        WebDriver driver = getDriver();
> +        driver.get("https://ref.eteam.work");
> +
> +        ProjectUtils.login(driver, "user1@tester.com", "ah1QNmgkEO");
> +
> +        WebElement calendar = driver.findElement(By.xpath("//p[contains(text(),'Calendar')]"));
> +        ProjectUtils.click(driver, calendar);
> +        WebElement newCalendar = driver.findElement(By.xpath("//div[@class='card-icon']/i"));
> +        newCalendar.click();
> +
> +        final String string = new UUID((long)(Math.random() * 1000000000), (long)(Math.random()
>
> UUID.randomUUID().toString()
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/195#discussion_r542752416>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARTKNRIARXWM5H6RQH4EDZ3SUZZEVANCNFSM4UZ24XLQ>
> .
>

2020-12-19 23:23 UTC, closed without merging