KH-PlatformaticaQA-AT
SergeiDemyanenko/PlatformaticaQA pull request #199
Opened 2020-12-14 01:54 UTC by Kateri-a

https://trello.com/c/abRhmtdg/144-entity-fields-edit-existing-record-at-1
https://trello.com/c/PaMGsHcM/145-entity-fields-edit-existing-record-at-2

2020-12-14 03:49 UTC, SergeiDemyanenko commented
Зачем отдельный класс, это должн быть метод в классе EntityFieldsTest

2020-12-14 03:50 UTC, SergeiDemyanenko requested changes
Зачем отдельный класс, это должн быть метод в классе EntityFieldsTest

2020-12-14 18:52 UTC, Kateri-a commented
> Зачем отдельный класс, это должн быть метод в классе EntityFieldsTest

Исправлено

2020-12-14 19:05 UTC, SergeiDemyanenko commented
Пусть повисит до завтра, потом поставлю approve

2020-12-14 19:13 UTC, Kateri-a commented
> Пусть повисит до завтра, потом поставлю approve
ОК

2020-12-14 22:00 UTC, Kateri-a commented
> > Пусть повисит до завтра, потом поставлю approve
> > ОК

Добавила еще 2 теста

2020-12-15 19:11 UTC, SergeiDemyanenko approved these changes

2020-12-15 19:12 UTC, merged