added positive test TCB-001 in EntityBoardInputTest.java
SergeiDemyanenko/PlatformaticaQA pull request #201
Opened 2020-12-14 07:08 UTC by 4stuntman4

in the test, we insert correct values in the fields and save the form. Verify that all values saved correctly. 
Not done - upload picture and verification of DateTime that has value 13/12/2020 18:02:42 and I have no idea how to compare it with minutes and sec - I always get different minutes and sec.

2020-12-14 16:52 UTC, Stan575 requested changes
Overall looks good, please do minor editions

2020-12-14 16:52 UTC, Stan575 commented on src/test/java/EntityBoardInputTest.java
> +
Delete empty lines

2020-12-14 16:52 UTC, Stan575 commented on src/test/java/EntityBoardInputTest.java
> +public class EntityBoardInputTest extends BaseTest {
Rename class to EntityBoardTest

2020-12-14 16:52 UTC, Stan575 commented on src/test/java/EntityBoardInputTest.java
> +        //Assert.assertEquals(createdRecordDateTime, currentDataTime, "Created dateTime issue"); // dodelat
Commented out code is prohibited per SergeiD

2020-12-14 19:16 UTC, 4stuntman4 commented on src/test/java/EntityBoardInputTest.java
> +
deleted

2020-12-14 19:17 UTC, 4stuntman4 commented on src/test/java/EntityBoardInputTest.java
> +public class EntityBoardInputTest extends BaseTest {
renamed

2020-12-14 19:17 UTC, 4stuntman4 commented on src/test/java/EntityBoardInputTest.java
> +        //Assert.assertEquals(createdRecordDateTime, currentDataTime, "Created dateTime issue"); // dodelat
deleted

2020-12-15 02:41 UTC, closed without merging

2020-12-15 02:41 UTC, 4stuntman4 commented
closed due to unresolved issues