Ik board edit
SergeiDemyanenko/PlatformaticaQA pull request #204
Opened 2020-12-14 15:21 UTC by irina0606

2020-12-14 16:34 UTC, Stan575 requested changes

2020-12-14 16:34 UTC, Stan575 commented on src/test/java/EditBoardEditTest.java
> +public class EditBoardEditTest extends BaseTest {
Rename class to EntityBoardTest

2020-12-14 16:34 UTC, Stan575 commented on src/test/java/EditBoardEditTest.java
> +
Remove empty line

2020-12-14 16:34 UTC, Stan575 commented on src/test/java/EditBoardEditTest.java
> +        /*WebElement calendar1 = driver.findElement(By.xpath("//input[@id='date']"));
Commented out code is prohibited

2020-12-14 16:34 UTC, Stan575 commented on src/test/java/EditBoardEditTest.java
> +
Delete empty lines

2020-12-14 16:38 UTC, Stan575 requested changes

2020-12-14 16:38 UTC, Stan575 commented on debug.log
> +[1204/164817.046:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Delete debug.log

2020-12-15 01:31 UTC, Stan575 approved these changes
Looking good

2020-12-15 19:07 UTC, SergeiDemyanenko requested changes
Работа над двумя тестами в одном PR

2020-12-15 19:07 UTC, SergeiDemyanenko commented
Необходимо добавить ссылку на задачу в PR

2020-12-17 02:18 UTC, 4stuntman4 requested changes
пул реквест не соответствует заданию - много реализованных задач в этом реквесте

2020-12-17 02:18 UTC, 4stuntman4 commented on src/test/java/EntityBoardTest.java
> +
это фто за пустые строчки?

2020-12-17 02:18 UTC, 4stuntman4 commented on src/test/java/EntityBoardTest.java
> +        //log in
комментариев быть не должно тут и так все понятно

2020-12-17 13:56 UTC, closed without merging