Entity Default.
SergeiDemyanenko/PlatformaticaQA pull request #210
Opened 2020-12-14 23:05 UTC by GalinaRuban

Checked default values, updated them and checked saved values.

https://trello.com/c/O16HVZPS/21-entity-default-input-new-record-with-new-values

2020-12-15 19:01 UTC, SergeiDemyanenko commented on src/test/java/EntityDefaultTest.java
> +//            Assert.assertEquals(allElementsText, textArray);
Закоментированный код не допустим

2020-12-15 19:02 UTC, SergeiDemyanenko commented on src/test/java/EntityDefaultTest.java
> +        //uploadPicture.sendKeys("C:\\Users\\Galina\\Desktop\\IMG_8992.JPG");
Закоментированный код не допустим

2020-12-15 19:02 UTC, SergeiDemyanenko requested changes
Закоментированный код не допустим

2020-12-16 02:19 UTC, GalinaRuban commented on src/test/java/EntityDefaultTest.java
> +        //uploadPicture.sendKeys("C:\\Users\\Galina\\Desktop\\IMG_8992.JPG");
Удалила, просто не знала как это обойти. На локальной машине он проходил, но тк путь к фото и файлу с локального компа, не уверена была что тест будет проходить у всех

2020-12-16 02:22 UTC, GalinaRuban commented on src/test/java/EntityDefaultTest.java
> +//            Assert.assertEquals(allElementsText, textArray);
Deleted all comments

2020-12-16 04:01 UTC, GalinaRuban commented
https://trello.com/c/O16HVZPS/21-entity-default-input-new-record-with-new-values

2020-12-16 06:46 UTC, closed without merging