EntityDefaultEdit-BM
SergeiDemyanenko/PlatformaticaQA pull request #211
Opened 2020-12-14 23:05 UTC by BogdanQA

2020-12-15 18:59 UTC, SergeiDemyanenko requested changes
Необходимо добавить ссылку на задачу в PR

2020-12-15 19:00 UTC, SergeiDemyanenko commented
В одном PR работать только над одним тестом.

2020-12-23 06:55 UTC, PeterKuzyk approved these changes

2020-12-23 06:58 UTC, sergeonevdah approved these changes

2020-12-23 07:08 UTC, closed without merging

2020-12-23 07:09 UTC, PeterKuzyk commented
Created a  correct  class