Assembly ad00
SergeiDemyanenko/PlatformaticaQA pull request #226
Opened 2020-12-15 15:58 UTC by assemblyad

Implemented automation for user story  Entity = Default: Input (New record with default values)

2020-12-15 16:08 UTC, SergeiDemyanenko requested changes

2020-12-15 16:08 UTC, SergeiDemyanenko commented on debug.log
> +[1210/173531.788:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
Зачем это в PR?

2020-12-15 16:08 UTC, SergeiDemyanenko commented on src/test/java/EntityDefaultTest.java
> +  //private WebDriver driver = getDriver(); //question here
Закомментированный код недопустим в PR

2020-12-15 16:09 UTC, SergeiDemyanenko commented
Почему в PR добавлено 3 теста и отредактирован еще один, это нужно было по задаче?

2020-12-15 16:09 UTC, SergeiDemyanenko commented
Было бы хорошо иметь ссылку на задачу в этом PR

2020-12-15 16:44 UTC, assemblyad commented
> Почему в PR добавлено 3 теста и отредактирован еще один, это нужно было по задаче?



> Почему в PR добавлено 3 теста и отредактирован еще один, это нужно было по задаче?

Написано два автоматических теста, первый покрывает главную форму и встроенную это и есть первые два мануальных теста. Второй автоматический тест покрывает третий мануальный. Я бы сказал что так и требовалось

2020-12-15 16:54 UTC, assemblyad commented
> Было бы хорошо иметь ссылку на задачу в этом PR

Added a task to PR

2020-12-16 17:48 UTC, closed without merging

2020-12-16 17:49 UTC, assemblyad commented
I close this one due too much complication and new one will be opened