Automated test for input new record in Export page
SergeiDemyanenko/PlatformaticaQA pull request #228
Opened 2020-12-15 17:17 UTC by talexand

Pename method
Link to the issue:

https://trello.com/c/xxH4ZXNK/217-entity-export-input-new-record-at

2020-12-15 18:52 UTC, SergeiDemyanenko approved these changes

2020-12-17 07:43 UTC, SergeiDemyanenko requested changes
Тебе необзодимо сделать merge из main

2020-12-17 21:22 UTC, natxs approved these changes

2020-12-18 20:18 UTC, SergeiDemyanenko approved these changes

2020-12-18 20:18 UTC, merged