Entity Readonly: Insert (new)
SergeiDemyanenko/PlatformaticaQA pull request #229
Opened 2020-12-15 17:46 UTC by OlesiaKazmirchuk

2020-12-15 18:42 UTC, SergeiDemyanenko requested changes
Имя класса и имя метода теста необходимо привести в соответствие с правилами

2020-12-15 18:42 UTC, SergeiDemyanenko commented on src/test/java/EntityReadonlyInsertTest.java
> +        //Assert.assertTrue(Boolean.parseBoolean(driver.findElement(By.xpath("//button[contains(text(),'+')]")).getAttribute("disabled")));
Комментарии в коде не допустимы

2020-12-15 20:43 UTC, OlesiaKazmirchuk commented on src/test/java/EntityReadonlyInsertTest.java
> +        //Assert.assertTrue(Boolean.parseBoolean(driver.findElement(By.xpath("//button[contains(text(),'+')]")).getAttribute("disabled")));
I corrected everything. Could you please merge changes?

2020-12-16 05:17 UTC, denisumanetssf approved these changes
Test case is in Ignore because of the bug below

https://trello.com/c/VIdT25je/33-user-is-able-to-introduce-data-when-adds-new-readonly-record

2020-12-16 05:22 UTC, merged