Change class name
SergeiDemyanenko/PlatformaticaQA pull request #232
Opened 2020-12-15 21:51 UTC by Stan575

Class name change to match entity name in the app
Add mac hidden file DS_Store to .gitignore

2020-12-15 22:44 UTC, SergeiDemyanenko requested changes
Раздели на 2 отдельных PR:
- рефакторинг

2020-12-15 23:41 UTC, Stan575 commented
Removed editing .gitignore from this PR

2020-12-15 23:49 UTC, Stan575 commented
Editing .gitignore PR: https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/233

2020-12-16 00:02 UTC, Stan575 commented
> Раздели на 2 отдельных PR:
> 
> * рефакторинг
> * редактирование .gitignore

Separated changes, PR for gitignore: https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/235

2020-12-16 02:15 UTC, Stan575 commented
There are problems in code, no review needed till test fixed.

2020-12-17 07:40 UTC, SergeiDemyanenko requested changes

2020-12-17 07:40 UTC, SergeiDemyanenko commented on src/test/java/EntityFieldsOpsTest.java
> +        ProjectUtils.goAndLogin(getDriver());
Заменить эту строку на ProjectUtils.loginProcedure(driver);

2020-12-17 20:06 UTC, Stan575 commented
EntityFieldOpsTest.fieldOpsView needs complete refactoring. 
[Task in Trello](https://trello.com/c/YbjNjFxf/238-fieldopsview-test-error)
Closing this PR

2020-12-17 20:06 UTC, closed without merging