add fieldInputNewRecordTest in EntityFieldsTest
SergeiDemyanenko/PlatformaticaQA pull request #242
Opened 2020-12-16 05:49 UTC by lenagrinen

2020-12-16 07:00 UTC, GalinaRuban commented
My pull request was stopped by Travis for the same reason.

2020-12-16 18:35 UTC, SergeiDemyanenko requested changes
Ссылку на задачу?

2020-12-16 20:08 UTC, lenagrinen commented
https://trello.com/c/czZXNks1/164-entity-copyfields-input-new-record-tc-1

2020-12-16 20:39 UTC, SergeiDemyanenko commented
> 
> 
> https://trello.com/c/czZXNks1/164-entity-copyfields-input-new-record-tc-1

Нужно добавить в description of PR

2020-12-16 20:45 UTC, lenagrinen commented
Я нашла как изменить/добавить title, ты это имел ввиду?)

2020-12-16 23:53 UTC, lenagrinen commented
> Я нашла как изменить/добавить title, ты это имел ввиду?)



> > https://trello.com/c/czZXNks1/164-entity-copyfields-input-new-record-tc-1
> 
> Нужно добавить в description of PR

кажется дошло) Посмотри, пожалуйста!

2020-12-17 07:35 UTC, SergeiDemyanenko requested changes

2020-12-17 07:35 UTC, SergeiDemyanenko commented on src/test/java/EntityFieldsTest.java
> +        ProjectUtils.login(driver, "user142@tester.com", "ymEDvCl2fG");
Заменить эти строки на ProjectUtils.loginProcedure(driver);

2020-12-17 07:35 UTC, SergeiDemyanenko commented
> 
> 
> > Я нашла как изменить/добавить title, ты это имел ввиду?)
> 
> > > https://trello.com/c/czZXNks1/164-entity-copyfields-input-new-record-tc-1
> > 
> > 
> > Нужно добавить в description of PR
> 
> кажется дошло) Посмотри, пожалуйста!

Да, так должно быть

2020-12-18 00:00 UTC, lenagrinen commented on src/test/java/EntityFieldsTest.java
> +        ProjectUtils.login(driver, "user142@tester.com", "ymEDvCl2fG");
I did it.

2020-12-20 02:29 UTC, SashaKolsky commented on src/test/java/EntityFieldsTest.java
> +        Thread.sleep(500);
Sleep was the only thing that helped fix the occasional errors.

2020-12-20 06:50 UTC, SashaKolsky approved these changes

2020-12-20 06:52 UTC, SashaKolsky approved these changes
Сергей, что-то я боролся с апрувалом. Но GitHub пишет что он хочет подтверждения именно от тебя.

2020-12-21 02:12 UTC, SergeiDemyanenko approved these changes

2020-12-21 02:12 UTC, merged