Prudka  export delete
SergeiDemyanenko/PlatformaticaQA pull request #285
Opened 2020-12-18 00:04 UTC by viktoriia1975

https://trello.com/c/tVX2MkyF/261-entity-export-deletecopy

2020-12-18 07:06 UTC, SashaKolsky requested changes
Исправляй мелочи, а так все хорошо - молодец!

2020-12-18 07:06 UTC, SashaKolsky commented on src/test/java/EntityExportDeleteTest.java
> +    public void inputRecordTest() {
Так как карточка с createTest еще никем не закрыта, можешь вынести создание записи в отдельный тест метод (insertTest) и написать комментарий (в карточке наверное лучше тоже написать) что он тут временно пока "хозяин" этого задания не напишет свой.

И использовать запуск с зависимостями как показывали на прошлой лекции (через аннотацию):
 @Test(dependsOnMethods = "insertRecord")

2020-12-18 07:06 UTC, SashaKolsky commented on src/test/java/EntityExportDeleteTest.java
> +        //verify Entity:View tickets
Непонятен комментарий, зачем он здесь? Если ничего не поясняет для читателя кода, то надо убрать.

2020-12-18 14:34 UTC, viktoriia1975 commented on src/test/java/EntityExportDeleteTest.java
> +    public void inputRecordTest() {
я так и делала, но т.к был создан вчера новый логин- то когда заходишь на сайт все записи чистяться и мне пришлось все мои методы объединить в один.

2020-12-18 14:34 UTC, viktoriia1975 commented on src/test/java/EntityExportDeleteTest.java
> +public class EntityExportDeleteTest extends BaseTest {
EntityExportTest такой класс уже в мейн ветке есть.

2020-12-19 06:59 UTC, SergeiDemyanenko commented on src/test/java/EntityExportDeleteTest.java
> +public class EntityExportDeleteTest extends BaseTest {
Значит нужно добавить твои тесты в тот класс или это разные user story?

2020-12-19 14:48 UTC, closed without merging