SB  Calendar edit
SergeiDemyanenko/PlatformaticaQA pull request #298
Opened 2020-12-18 06:29 UTC by Seid31

https://ref.eteam.work/index.php?action=action_list&entity_id=32

2020-12-19 06:57 UTC, SergeiDemyanenko requested changes
Все отлично, только 2 момента:
- свяжи тесты как мы это рассматривали на занятии, сделай один тест зависимый от другова
- добавь валидацию в конце каждого теста (запись была создана, запись была изменена)

2020-12-23 06:01 UTC, Seid31 commented
Done, please check and approve :)

2020-12-23 06:09 UTC, SergeiDemyanenko approved these changes

2020-12-23 06:14 UTC, Stan575 approved these changes

2020-12-23 06:21 UTC, merged