AS -  Chevron add & edit
SergeiDemyanenko/PlatformaticaQA pull request #363
Opened 2020-12-23 01:44 UTC by pomidorych

2020-12-24 07:20 UTC, SergeiDemyanenko requested changes

2020-12-24 07:20 UTC, SergeiDemyanenko commented on src/test/java/EntityChevronTest.java
> +    }
В последнем видео (G) я рассказывал, что так делать не стоит.

2020-12-28 06:12 UTC, pomidorych commented on src/test/java/EntityChevronTest.java
> +    }
В видео говорится, что так делать не стоит, потому что метод используется один раз в коде и подразумевается, что в тесте только одна запись для работы. 
1. Поскольку тест другого студента добавляет внутри метода свои данные, а не привязан к методу addRecord(), то образуются несколько записей в таблице. С моим методом я не зависим от его теста и работаю только со своей записью (валидирую именно свои данные, нажимаю кнопку Edit и View именно у своей записи).
2. У меня метод используется 2 раза.

2021-01-30 00:01 UTC, Stan575 commented
Closed as inactive

2021-01-30 00:01 UTC, closed without merging