Entity = Export: Input (COPY)
SergeiDemyanenko/PlatformaticaQA pull request #370
Opened 2020-12-24 05:22 UTC by Marina-sukhova

The firts PR

2020-12-24 09:04 UTC, Stan575 requested changes

2020-12-24 09:04 UTC, Stan575 commented on src/test/java/EntityExportTest.java
> +        Assert.assertTrue(true, "Error saving entity");
assertTrue(true) will always pass, you know :D 
there's a bug (not fixed yet) everybody knows about, can you wrap it in a different way?

2020-12-24 12:13 UTC, viktoriia1975 commented on src/test/java/EntityExportTest.java
> +    //Negative test String to Int Field
Я не вижу еще ссылку на Трелло задачу. И плюс тест view изменился. Посмотри.

2020-12-24 23:01 UTC, Stan575 commented on src/test/java/EntityExportTest.java
> +        Assert.assertTrue(true, "Error saving entity");
it's actually expected behavior at this time, not a bug

2020-12-25 03:52 UTC, Stan575 approved these changes
Nicely done!

2020-12-25 03:54 UTC, Stan575 reviewed
Added a note on line 253

2020-12-25 03:54 UTC, Stan575 commented on src/test/java/EntityExportTest.java
> +        Assert.assertEquals("Error saving entity", errorText);
public static void assertEquals(String actual, String expected)
assertEquals accepts actual result as first argument, and expected result as second argument, you can swap them to use it right way

2020-12-25 03:57 UTC, Marina-sukhova commented on src/test/java/EntityExportTest.java
> +        Assert.assertEquals("Error saving entity", errorText);
Got you!

2020-12-25 08:01 UTC, Stan575 commented
@Marina-sukhova also you need to add Trello task

2021-01-11 04:07 UTC, PeterKuzyk approved these changes

2021-01-11 04:07 UTC, merged