Refactor EntityFieldOpsDeleteTest method
SergeiDemyanenko/PlatformaticaQA pull request #378
Opened 2020-12-25 02:04 UTC by VolgaStaravoitava

2020-12-25 07:49 UTC, Stan575 requested changes

2020-12-25 07:49 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        WebElement dropDown = getWait(3000).until(ExpectedConditions.elementToBeClickable(dropdownMenu));
getWait accepts as an argument value in seconds, better to set it to 3 instead of 3000, just in case of random failure we don't want to wait for 50 min

2020-12-25 07:54 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        WebElement dropDown = getWait(3000).until(ExpectedConditions.elementToBeClickable(dropdownMenu));
can you ping me in slack @Stan Aretinskiy (Stan575) ?

2020-12-25 18:22 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +        WebElement dropDown = getWait(3000).until(ExpectedConditions.elementToBeClickable(dropdownMenu));
Updated

2020-12-26 00:13 UTC, Stan575 approved these changes

2020-12-26 20:45 UTC, SergeiDemyanenko approved these changes

2020-12-26 20:46 UTC, merged