Refactor EntityFieldOpsTest
SergeiDemyanenko/PlatformaticaQA pull request #380
Opened 2020-12-25 03:27 UTC by Stan575

2020-12-25 23:10 UTC, VolgaStaravoitava requested changes

2020-12-25 23:10 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +    }
Вместо click() нужно использовать ProjectUtils.click() метод.

2020-12-25 23:20 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +    }
> Вместо click() нужно использовать ProjectUtils.click() метод.
Here I disagree. ProjectUtils.click() uses JavaScript for clicking on an element, which should be the last option in your arsenal if nothing else works. That click happens under the hood of browser, so it means element will be clicked if it exists in html document, even if that element is not visible at all. I try to avoid JavaScript clicks at all cost if possible.

2020-12-25 23:28 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +    }
> Вместо click() нужно использовать ProjectUtils.click() метод.

I disagree on this. ProjectUtils.click() utilizes JavaScript to forcefully click on element, it happens under the hood in browser. It'll work if an element exists in html page document even if not visible in ui. So I use it as the last option if nothing else works. Not a good practice to abuse  `((JavaScript) driver).esecuteScript("arguments[0].click()", <element>)` in my opinion.

2020-12-28 01:14 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +    }
> Вместо click() нужно использовать ProjectUtils.click() метод.

Problem with clicking 'save' button resolved by commits:
[540b85e8f2db48e40aa9c5f117b94c0acd39cf24](https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/380/commits/540b85e8f2db48e40aa9c5f117b94c0acd39cf24)
[cdaa5b085c8e4fa0cae74347d482571f4471c891](https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/380/commits/cdaa5b085c8e4fa0cae74347d482571f4471c891)

2020-12-28 04:17 UTC, VolgaStaravoitava requested changes

2020-12-28 04:17 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +        String[] values = {null, SWITCH_VALUE, DEFAULT_DROPDOWN, REFERENCE, MULTI_REFERENCE, REFERENCE_WITH_FILTER,
null в начале массива выглядит странно

2020-12-28 04:17 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +    public void viewBaseRecordRefExist() throws InterruptedException {
viewBaseRecordRefExistTest()

2020-12-28 04:17 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +    public void deleteRecord() throws InterruptedException {
deleteRecordTest()

2020-12-28 04:17 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +        waitInvisibilityOf(2, record);
2-почему 2, что это значит? Что мы здесь делаем?

2020-12-28 04:17 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +        Assert.assertEquals(deletedItems.size(), 1);
Тест должен проверять, что запись с соответствующим Reference появилась в корзине.

2020-12-28 05:17 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        return getDriver().findElement(By.tagName("body")).getSize().getHeight() - 25 > element.getLocation().getY();
Purpose of this method is to avoid errors when running tests locally on a machine with smaller screen. It checks if passed web element can be seen in the browser window right at the moment. 25 is a little more than half size of 'save' button, method click() is making click in the middle of an element ([more about it here](https://w3c.github.io/webdriver/#element-click)) so some scrolling required for proper operation. Comments are not desirable per Sergei. Will change method name to be technically correct.

2020-12-28 05:17 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +    public void createNewRecord() {
This wasn't a part of our naming convention, testng doesn't require to have 'test' in test method name since we have special annotation before for each test. Will rename all tests.

2020-12-28 05:17 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        String[] values = {null, SWITCH_VALUE, DEFAULT_DROPDOWN, REFERENCE, MULTI_REFERENCE, REFERENCE_WITH_FILTER,
That is for an element with no text, later (lines 221-225) verification happens in for loop (initialized with i = 0) against List of web elements.

2020-12-28 05:18 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        waitInvisibilityOf(2, record);
2 is waiting timeout in seconds for the element to disappear.

2020-12-28 05:18 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        Assert.assertEquals(deletedItems.size(), 1);
At this moment mentioned verification blocked by [bug](https://trello.com/c/OPR1zaFw/51-corrupted-data-shown-for-fields-ops-deleted-record-in-recycle-bin), need to add that after bug goes away.

2020-12-28 05:28 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        waitInvisibilityOf(2, record);
Going to change arguments order to make it easier to understand

2020-12-28 05:31 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +        return getDriver().findElement(By.tagName("body")).getSize().getHeight() - 25 > element.getLocation().getY();
Как я понимаю, то это некоторая замена ProjectUtils.click метода.
Т.к. замена стала сложнее оригинального метода, предлагаю вернуться к ProjectUtils.click.
Если же оставлять данный метод, хотя лучше всё-таки лучше вернуться к использованию ProjectUrils.click, то нужно добавить описание в метод, т.к. он несет свою логику, которую никто не вспомнит уже через месяц, будет сложно разобраться, что за 25 и зачем это было сделано.

2020-12-28 05:56 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +    public void createNewRecord() {
It's good practice to name test methods *Test, in general.

2020-12-28 06:00 UTC, VolgaStaravoitava commented on src/test/java/EntityFieldOpsTest.java
> +        Assert.assertEquals(deletedItems.size(), 1);
1. Sergei mentioned that not touch others tests.
2. As it's was done, you have to mark the test with @Ignore annotation with link to the ticket, and place TODO section.

2020-12-28 06:03 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        return getDriver().findElement(By.tagName("body")).getSize().getHeight() - 25 > element.getLocation().getY();
Although result is the same, it's not a substitute for clicking with JavaScript. This method is the right way workaround for people with not big screens to run tests locally without false negative failures. Right way ain't always the better one lol
If screen allows to have browser viewport hight over 920px this problem doesn't exist

2020-12-28 06:07 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        Assert.assertEquals(deletedItems.size(), 1);
You're right, will put it back as it was

2020-12-28 06:30 UTC, Stan575 commented on src/test/java/EntityFieldOpsTest.java
> +        Assert.assertEquals(deletedItems.size(), 1);
It seems like this PR comes out with lots of back and forth changes and too many commits. I have a better idea to open another one with clean track record instead of this. 
I'm sorry about touching your test

2020-12-28 06:31 UTC, Stan575 commented
Closed upon complications with code.

2020-12-28 06:31 UTC, closed without merging