add deleteRecord
SergeiDemyanenko/PlatformaticaQA pull request #389
Opened 2020-12-26 07:04 UTC by AleksandrNiceFly

Тикеты не делал на эту задачу ,больше функционал интересно тренировать , спасибо за проверки) 
Подсказывайте ,пожалуйста ,люди добрые, как улучшать код и в какую сторону двигаться новичку! Благодарю

2020-12-26 21:01 UTC, SergeiDemyanenko commented
> 
> 
> Тикеты не делал на эту задачу ,больше функционал интересно тренировать , спасибо за проверки)
> Подсказывайте ,пожалуйста ,люди добрые, как улучшать код и в какую сторону двигаться новичку! Благодарю

Нас тут много и общий процесс — это не прихоть, а необходимость, которая позволяет поддерживать порядок и понимание происходящего, если все студенты начнут делать не то, что они хотят, а процесса не будет вообще, встанем и разойдемся. Сделай тикет и добавь в описание PR ссылку на него.

2020-12-27 01:50 UTC, AleksandrNiceFly commented
> > Тикеты не делал на эту задачу ,больше функционал интересно тренировать , спасибо за проверки)
> > Подсказывайте ,пожалуйста ,люди добрые, как улучшать код и в какую сторону двигаться новичку! Благодарю
> 
> Нас тут много и общий процесс — это не прихоть, а необходимость, которая позволяет поддерживать порядок и понимание происходящего, если все студенты начнут делать не то, что они хотят, а процесса не будет вообще, встанем и разойдемся. Сделай тикет и добавь в описание PR ссылку на него.

Понял, извиняюсь , сейчас сделаю/

2020-12-27 02:47 UTC, Stan575 requested changes

2020-12-27 02:47 UTC, Stan575 commented on src/test/java/EnityFieldsCopyTest.java
> +        Assert.assertEquals(proof.getText(), "EDIT fields");
Your test will never get to verification of text if the element with that text not found. Better to use different xpath, something like 
`//span[contains(text(), 'Title:')]/b`

2020-12-27 03:04 UTC, AleksandrNiceFly commented on src/test/java/EnityFieldsCopyTest.java
> +        Assert.assertEquals(proof.getText(), "EDIT fields");
oh yeah , you right my friend !!!! Thank you !!!!

2020-12-27 03:21 UTC, AleksandrNiceFly commented
https://trello.com/c/RP7tlb7I/359-entity-fields-delete-copy

2020-12-27 05:15 UTC, AleksandrNiceFly commented
Stan огромное тебе спасибо за твое время и советы!

2020-12-27 05:25 UTC, Stan575 approved these changes

2021-01-06 03:18 UTC, closed without merging