EntityDefaultDelete
SergeiDemyanenko/PlatformaticaQA pull request #392
Opened 2020-12-27 07:33 UTC by ValentinaQA

2020-12-27 20:55 UTC, ke-de-ve reviewed
This should be part of the EntityDefaultTest class. That class already has code to create new EntityDefault records.

2020-12-27 21:16 UTC, Stan575 commented
Add trello task to PR description

2020-12-29 18:20 UTC, ValentinaQA commented
> This should be part of the EntityDefaultTest class. That class already has code to create new EntityDefault records.

I have falling tests in EntityDefaultTest class, that why I can`t write in this class

2020-12-29 18:21 UTC, ValentinaQA commented
> Add trello task to PR description

https://trello.com/c/A5CS1n1p/273-entity-default-delete-at
Done

2020-12-29 18:34 UTC, Stan575 commented
> > This should be part of the EntityDefaultTest class. That class already has code to create new EntityDefault records.
> 
> I have falling tests in EntityDefaultTest class, that why I can`t write in this class

Right now EntityDefaultTest has only two enabled tests running independently, your tests works just fine in there

2020-12-29 18:42 UTC, Stan575 requested changes
This test looks good overall, I think it should be moved to EntityDefaultTest class though

2020-12-29 18:42 UTC, Stan575 commented on src/test/java/EntityDefaultDeleteTest.java
> +    public void EntityDefaultDelete() throws InterruptedException {
Rename test method with lower case first letter, and remove "throws InterruptedException" since your test doesn't have hardcoded waiters

2020-12-29 19:41 UTC, closed without merging