OB arithmetic function test refactor
SergeiDemyanenko/PlatformaticaQA pull request #400
Opened 2020-12-29 03:25 UTC by Burdishka

Refactoring user story: https://trello.com/c/klAEa9DY/322-entityarithmeticfunctiontest-clickarithmeticfunction

2020-12-29 04:07 UTC, guram21 approved these changes

2020-12-29 04:26 UTC, Stan575 requested changes
Overall looks pretty good
Minor changes requested

2020-12-29 04:26 UTC, Stan575 commented on src/test/java/EntityArithmeticFunctionTest.java
> +        Assert.assertEquals(String.valueOf(number1 / number2), driver.findElement(DIV_VIEW_MODE).getText());
Please change arguments oder for assertEquals in these lines 
`assertEquals(String actual,String expected)`

2020-12-29 04:26 UTC, Stan575 commented on src/test/java/EntityArithmeticFunctionTest.java
> +        Assert.assertEquals(String.valueOf(number1 / number2), driver.findElement(DIV_EDIT_MODE).getAttribute("value"));
Change arguments oder

2020-12-29 04:26 UTC, Stan575 commented on src/test/java/EntityArithmeticFunctionTest.java
> +        Assert.assertEquals(ERROR_MESSAGE, driver.findElement(ERROR).getText());
Change arguments oder

2020-12-30 03:38 UTC, Stan575 approved these changes
Well done!

2020-12-30 03:49 UTC, merged