refactoring, moved my tests to the new class
SergeiDemyanenko/PlatformaticaQA pull request #406
Opened 2020-12-31 02:42 UTC by MaxBurdin

https://trello.com/c/sZaywFvV/325-entityassigntest

2020-12-31 04:06 UTC, Burdishka requested changes

2020-12-31 04:06 UTC, Burdishka commented on src/test/java/EntityAssignTest1.java
> +@Run(run= RunType.Multiple)
run = RunType.Multiple - пробел после run

2020-12-31 04:29 UTC, MaxBurdin commented on src/test/java/EntityAssignTest1.java
> +        String anotherUser = "user" + (int)(Math.random() * (249 - 100 + 1) + 100) + "@tester.com";
эта переменная используется только в методе editTest(). зачем делать ее полем?

2020-12-31 05:01 UTC, SergeiDemyanenko requested changes
Мог бы ты объяснить, зачем ты удалил тесты из одного класса и добавил другой класс?

2020-12-31 05:39 UTC, MaxBurdin commented
> Мог бы ты объяснить, зачем ты удалил тесты из одного класса и добавил другой класс?

над тестом одной сущности работают два человека. ты попросил перенести мои тесты в отдельный класс
с 46 минуты https://youtu.be/qUkQpKB9YQo?list=PL6Gtav8N4O7jvKFj1SzQwMHCxRHExGC7I&t=2759

2020-12-31 07:35 UTC, Stan575 reviewed
See comments on lines 30 and 80

2020-12-31 07:35 UTC, Stan575 commented on src/test/java/EntityAssignTest1.java
> +        ProjectUtils.click(driver, driver.findElement(By.xpath("//a[contains(@href, 'create&entity_id=37')]")));
Don't abuse ProjectUtils.click(), line 30 can be replaced with:
`driver.findElement(By.xpath("//i[contains(text(), 'create_new')]")).click();`

2020-12-31 07:35 UTC, Stan575 commented on src/test/java/EntityAssignTest1.java
> +        Assert.assertTrue(driver.findElements(By.xpath("//div[contains(text(),'" + STRING_INP + "')]")).isEmpty());
I see here performance issue, in this line test waits 10 seconds (default implicit wait setup) for element/or elements that don't exist. There should be a way to avoid that unnecessary long wait. One of possible solutions would be to wait till page loaded, some element shown, turn implicit wait off, and then verify no unexpected element found, after that set implicit wait back to default 10 sec if other tests depend on this one. Another one could be to use short explicit wait and handle timeout exception as expected outcome.
Same things happen in lines 92 and 102

2021-01-02 22:40 UTC, MaxBurdin commented on src/test/java/EntityAssignTest1.java
> +        Assert.assertTrue(driver.findElements(By.xpath("//div[contains(text(),'" + STRING_INP + "')]")).isEmpty());
but what if there is a bug and the element exists and it takes time to load it? will the test pass without detecting the existing element?

2021-01-02 23:26 UTC, Stan575 commented on src/test/java/EntityAssignTest1.java
> +        Assert.assertTrue(driver.findElements(By.xpath("//div[contains(text(),'" + STRING_INP + "')]")).isEmpty());
on 'My Assignments' page I'd make it implicitly wait till element with xpath `//h3[contains(text(), 'Tasks for')]` is visible and then explicitly wait no more than 2 sec for any assignment  element

2021-01-03 22:40 UTC, closed without merging