refactoring, moved my tests to the new class
SergeiDemyanenko/PlatformaticaQA pull request #409
Opened 2021-01-03 22:30 UTC by MaxBurdin

https://trello.com/c/sZaywFvV/325-entityassigntest

made changes that were suggested from here https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/406
 removed priorities and blank lines, moved changeUser() before the tests, made some xpapthes shorter, removed field with a link and replaced its verification with text verification, changed implicit wait before checking invisible element to avoid performance issues

 ignored EntityDefaultTest https://trello.com/c/EXVzrgLX/390-entitydefaulttest

2021-01-07 05:01 UTC, SergeiDemyanenko requested changes
Переименуй EntityAssignTest1 в EntityAssign1Test

2021-01-07 06:29 UTC, SergeiDemyanenko commented
Ты добавил соотвествующие тикеты по тем тестам которые ты пометил как Ignore?

2021-01-07 06:31 UTC, MaxBurdin commented
> Ты добавил соотвествующие тикеты по тем тестам которые ты пометил как Ignore?

да. я сделал один тикет для всего класса https://trello.com/c/FsFJRsMr/409-entityboardtest

2021-01-07 14:41 UTC, ArinaJur approved these changes
LGTM

2021-01-07 20:54 UTC, Stan575 approved these changes

2021-01-08 00:42 UTC, SergeiDemyanenko commented
> 
> 
> > Ты добавил соотвествующие тикеты по тем тестам которые ты пометил как Ignore?
> 
> да. я сделал один тикет для всего класса https://trello.com/c/FsFJRsMr/409-entityboardtest

В тикете указана ошибка только в editBoard. Зависящие от него тесты не стоит игнорить, они и так запускаться не будут, а так это вводит в заблуждение. Убери с них ignore.

2021-01-08 02:12 UTC, SergeiDemyanenko approved these changes

2021-01-08 02:12 UTC, merged