myFirstRefactoring
SergeiDemyanenko/PlatformaticaQA pull request #435
Opened 2021-01-09 11:04 UTC by AleksandrNiceFly

https://trello.com/c/R9INPKLK/419-entityfieldsalextestcopy

Ребят, не судите строго , пожалуйста. Подскажите ошибки и укажите советы! Спасибо!

2021-01-09 21:52 UTC, SergeiDemyanenko requested changes
Приведи имя класса к соотвествию нашим правилам.

2021-01-09 23:36 UTC, AleksandrNiceFly commented
Кроме этого нет замечаний? Может советы какие? СПАСИБО!

2021-01-10 18:27 UTC, SergeiDemyanenko requested changes

2021-01-10 18:27 UTC, SergeiDemyanenko commented on src/test/java/EntityFields2Test.java
> +    private static final By CREATE_newRecord = By.xpath("//i[text() = 'create_new_folder']");
Имя поля не соотвествует общему принципу наименования

2021-01-10 18:27 UTC, SergeiDemyanenko commented on src/test/java/EntityFields2Test.java
> +
Пустая строка в конце, зачем она?

2021-01-10 18:27 UTC, SergeiDemyanenko commented on src/test/java/EntityFields2Test.java
> +    private static final By INTEGER_LOCATOR = By.xpath("//td[4]/a/div");
Если ты даешь постфикс LOCATOR, то почему бы его не сделать для остальных полей?

2021-01-10 18:27 UTC, SergeiDemyanenko commented on src/test/java/EntityFields2Test.java
> +    private static final String NEW_INTEGER = "1996";
Может сделать постфикс для этих полей, чтобы было понятно, что это не локаторы, а данные?

2021-01-10 18:27 UTC, SergeiDemyanenko commented on src/test/java/EntityFields2Test.java
> +        WebDriverWait wait = new WebDriverWait(driver, 4);
Можно использовать getWebDriverWait() метод, чтобы получить базовый waiter

2021-01-10 18:27 UTC, SergeiDemyanenko commented on src/test/java/EntityFields2Test.java
> +        WebDriverWait wait = new WebDriverWait(driver, 4);
Можно использовать getWebDriverWait() метод, чтобы получить базовый waiter

2021-01-10 18:27 UTC, SergeiDemyanenko commented on src/test/java/EntityFields2Test.java
> +        Assert.assertEquals(rowInRecycleBin.size(), 1);
Нужно проверить, что запись исчезла из списка, а не то, что в корзине есть какая-то запись, может там не твая, а твоя запись все еще в списке.

2021-01-15 03:06 UTC, closed without merging