refactor
SergeiDemyanenko/PlatformaticaQA pull request #444
Opened 2021-01-11 01:21 UTC by MaslovStan

https://trello.com/c/CJsHMziG/424-entitycalendartest

2021-01-11 03:27 UTC, ke-de-ve requested changes

2021-01-11 03:27 UTC, ke-de-ve commented on src/test/java/EntityCalendarTest.java
> +        WebElement deleteRecord = driver.findElement(By.xpath("//b[contains(text(),'" + titleField + "')]"));
change to use String.format

2021-01-11 19:52 UTC, Stan575 requested changes

2021-01-11 19:52 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
> +        WebDriverWait wait = new WebDriverWait(driver, 10);
In every test Instead of creating new instance of WebDriverWait you can call getWebDriverWait(), it returns WebDriverWait set to 10 sec. Please delete this line

2021-01-11 19:52 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
>          wait.until(driver1 -> deleteRecord.isDisplayed());
replace wait with getWebDriverWait()

2021-01-11 19:52 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
> +        newEntityCalendarRecord();
Here you create new calendar record:
- is test logic allowing to use existing record?
- if so, is it possible to specify dependencies for tests, in other words make tests run in certain sequence?
Same applied to deleteRecord test

2021-01-11 19:52 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
> +    public void editRecord() throws InterruptedException {
This test doesn't use any hard sleep, delete `throws InterruptedException` from this line

2021-01-11 19:52 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
> +    public void deleteRecord() throws InterruptedException {
This test doesn't use any hard sleep, delete `throws InterruptedException` from this line

2021-01-11 21:12 UTC, Stan575 approved these changes

2021-01-18 19:37 UTC, ke-de-ve approved these changes
look good

2021-01-18 19:38 UTC, merged