Pom refactoring EntityFieldsTest and more
SergeiDemyanenko/PlatformaticaQA pull request #463
Opened 2021-01-13 14:57 UTC by Stan575

2021-01-13 16:45 UTC, irina0606 approved these changes
Looks good!

2021-01-13 16:57 UTC, PeterKuzyk submitted a review, later dismissed

2021-01-13 16:59 UTC, PeterKuzyk reviewed
This branch has conflicts that must be resolved

2021-01-13 17:06 UTC, PeterKuzyk approved these changes

2021-01-13 19:09 UTC, SergeiDemyanenko requested changes

2021-01-13 19:09 UTC, SergeiDemyanenko commented on src/test/java/model/BaseTablePage.java
> +    public WebElement getEntityIcon(int rowNumber) {
getRowEntityIcon?

2021-01-13 19:09 UTC, SergeiDemyanenko commented on src/test/java/model/BaseTablePage.java
> +        } catch (InterruptedException ignored) {}
Тут бы wait.until поставить вместо sleep

2021-01-13 19:09 UTC, SergeiDemyanenko commented on src/test/java/model/FieldsPage.java
> +    }
Зачем это если у родителя есть метод getRow

2021-01-13 22:28 UTC, Stan575 commented on src/test/java/model/BaseEditPage.java
> +        click(getWait(), saveButton);
changed

2021-01-13 22:28 UTC, Stan575 commented on src/test/java/model/BaseTablePage.java
> +    public WebElement getEntityIcon(int rowNumber) {
changed

2021-01-13 22:28 UTC, Stan575 commented on src/test/java/model/BaseTablePage.java
> +        } catch (InterruptedException ignored) {}
с wait.until иногда бывают ошибки (редко, но неприятно), так работает более стабильно

2021-01-13 22:28 UTC, Stan575 commented on src/test/java/model/FieldsPage.java
> +    }
getRow не возвращает User в списке строк

2021-01-13 23:13 UTC, Stan575 commented on src/test/java/model/FieldsPage.java
> +    }
getRow возвращает только видимый текст в элементах //td/a/div, и не возвращает пустые строки для элементов без текста, что используется в моих тестах

2021-01-14 02:05 UTC, Stan575 commented on src/test/java/model/BaseTablePage.java
> +        } catch (InterruptedException ignored) {}
Там есть еще спорные моменты, я не хочу работу над ними включать в этот пр

2021-01-14 04:00 UTC, ArinaJur commented on src/test/java/model/BaseEditPage.java
> +    @FindBy(css = "button[id*='save']")
Почему бы Save Button не искать по id? 
id = "pa-entity-form-save-btn"

2021-01-14 04:01 UTC, ArinaJur commented on src/test/java/model/BaseEditPage.java
> +    @FindBy(css = "button[id*='draft']")
@FindBy(id = "pa-entity-form-draft-btn")

2021-01-14 04:14 UTC, ArinaJur commented on src/test/java/model/BaseTablePage.java
> +        } catch (InterruptedException ignored) {}
Здесь стабильно без сбоев работал ProjectUtils.click(driver,    );

2021-01-14 04:24 UTC, Stan575 commented on src/test/java/model/BaseEditPage.java
> +    @FindBy(css = "button[id*='save']")
My preference here is using locator pointing to an element with tag "button" and "id" containing "save" in it

2021-01-14 04:24 UTC, Stan575 commented on src/test/java/model/BaseEditPage.java
> +    @FindBy(css = "button[id*='draft']")
cssSelector locator points to an element with tag "button" and "id" containing "draft"

2021-01-14 05:58 UTC, Stan575 commented on src/test/java/model/BaseTablePage.java
> +        } catch (InterruptedException ignored) {}
> Здесь стабильно без сбоев работал ProjectUtils.click(driver, WebElement element);
> Теперь есть ProjectUtils.jsClick(JavascriptExecutor executor, WebElement element)

New ProjectUtils.jsClick works same way as previous ProjectUtils.click, the difference is new method can use static JavascriptExecutor from BasePage (getExecutor), in this case we don't create new instance of JavascriptExecutor when  we click on element with JavaScript

2021-01-14 07:33 UTC, SergeiDemyanenko commented on src/test/java/model/FieldsPage.java
> +    }
Если нужно вернуть больше, то нужно использовать полиморфизм для этого класса

2021-01-14 07:41 UTC, SergeiDemyanenko approved these changes

2021-01-14 07:41 UTC, merged