Entity = ChildRecordsLoop
SergeiDemyanenko/PlatformaticaQA pull request #470
Opened 2021-01-14 06:24 UTC by GalinaRuban

Trello task - https://trello.com/c/aJ8M9Ruk/463-entitychildrecordsloop

Bug https://trello.com/c/zAnsbPM1/40-entity-child-records-loop-end-balance-is-not-calculating-properly-after-the-previously-created-record-was-edited was finally fixed, so pushing without ignore

2021-01-16 04:17 UTC, Stan575 approved these changes

2021-01-16 04:17 UTC, Stan575 commented on src/test/java/EntityChildRecordsLoopTest.java
> +        fillData("//tr//textarea[@id='t-68-r-9-amount']", String.valueOf(firstValuesPassed[9]));
is it possible to make a loop here?

2021-01-16 04:25 UTC, GalinaRuban commented on src/test/java/EntityChildRecordsLoopTest.java
> +        fillData("//tr//textarea[@id='t-68-r-9-amount']", String.valueOf(firstValuesPassed[9]));
I did that in view mode http://prntscr.com/wsgpz8, in edit mode the selectors are different. It's mode complicated since I would need to think about a method to play with numbers in selectors. Not sure if I ready for it yet...

2021-01-16 04:57 UTC, GalinaRuban commented on src/test/java/EntityChildRecordsLoopTest.java
> +        fillData("//tr//textarea[@id='t-68-r-9-amount']", String.valueOf(firstValuesPassed[9]));
Done with Stan's help

2021-01-16 05:20 UTC, SergeiDemyanenko requested changes

2021-01-16 05:20 UTC, SergeiDemyanenko commented on src/test/java/EntityChildRecordsLoopTest.java
> +        driver.navigate().back();
Это зачем в конце теста?

2021-01-16 05:20 UTC, SergeiDemyanenko commented on src/test/java/EntityChildRecordsLoopTest.java
> +        String partOfXpath = removeDecimal(endBalanceDigit) + "";
Нужно иначе конвертировать тип, так уже больше 10 лет никто не делает.

2021-01-16 05:20 UTC, SergeiDemyanenko commented on src/test/java/EntityChildRecordsLoopTest.java
> +        wait.until(d -> savedRecord.isDisplayed());
Это можно совместить?

2021-01-16 05:23 UTC, GalinaRuban commented on src/test/java/EntityChildRecordsLoopTest.java
> +        driver.navigate().back();
Убираю, осталось с того момента как один тест включал два, потом я его разделила и упустила этот момент

2021-01-16 05:25 UTC, GalinaRuban commented on src/test/java/EntityChildRecordsLoopTest.java
> +        wait.until(d -> savedRecord.isDisplayed());
Да, сделала так wait.until(d -> driver.findElement(By.xpath("//div[contains(text(),'" + partOfXpath + "')]")).isDisplayed());, т.е убрала переменную

2021-01-16 05:26 UTC, GalinaRuban commented on src/test/java/EntityChildRecordsLoopTest.java
> +        String partOfXpath = removeDecimal(endBalanceDigit) + "";
Не уверена, что знаю как..

2021-01-16 05:51 UTC, GalinaRuban commented on src/test/java/EntityChildRecordsLoopTest.java
> +        String partOfXpath = removeDecimal(endBalanceDigit) + "";
changed to String partOfXpath = Integer.toString(removeDecimal(endBalanceDigit))
Подсказали, сама бы долго думала еще)

2021-01-17 23:04 UTC, ArinaJur approved these changes

2021-01-18 00:27 UTC, merged