Vr 12
SergeiDemyanenko/PlatformaticaQA pull request #48
Opened 2020-12-06 22:21 UTC by viktoriiaret

2020-12-06 23:06 UTC, sergeonevdah commented
Внимательно прочитай условия задачи. Не вноси ни каких изменений в pom.xml

2020-12-06 23:09 UTC, sergeonevdah requested changes

2020-12-06 23:09 UTC, sergeonevdah commented on pom.xml
> -            <groupId>io.github.bonigarcia</groupId>
тут менять ничего не нужно

2020-12-06 23:16 UTC, viktoriiaret commented on pom.xml
> -            <groupId>io.github.bonigarcia</groupId>
это я неудачно коммент написала в pom файле) спасибо что сказал))
залила новый PR

2020-12-07 00:16 UTC, closed without merging

2020-12-07 00:16 UTC, sergeonevdah commented
closed