Oe pom entity default
SergeiDemyanenko/PlatformaticaQA pull request #495
Opened 2021-01-18 19:04 UTC by OxanaE

https://trello.com/c/Ew7XqiIn/427-pom-entitydefault-test
Refactored all tests in class to use POM except the part with embedded values

2021-01-18 23:06 UTC, Stan575 requested changes

2021-01-18 23:06 UTC, Stan575 commented on src/test/java/EntityDefaultTest.java
> +
assertion can be done in test using actual and expected data sets of the same type

2021-01-18 23:06 UTC, Stan575 commented on src/test/java/EntityDefaultTest.java
>          WebElement createEmbedD = driver.findElement(By.xpath("//button[@data-table_id='11']"));
move all interactions with browser to a page class

2021-01-19 00:36 UTC, OxanaE commented on src/test/java/model/DefaultEditPage.java
> +        element.sendKeys("\t");
sends tab. without it one of the fields don't work

2021-01-19 00:37 UTC, OxanaE commented on src/test/java/EntityDefaultTest.java
>          WebElement createEmbedD = driver.findElement(By.xpath("//button[@data-table_id='11']"));
this part is not yet refactored

2021-01-19 01:14 UTC, OxanaE commented on src/test/java/model/BaseTablePage.java
> +        return getRows().get(rowNumber).findElements(By.xpath(xpath)).stream()
in my code old functionality and method signature is preserved so none of the existing code gets affected. the new code adds flexibility without code duplication. see lines 57 .. 59

`
    public List<String> getRow(int rowNumber) {
        return getRow(rowNumber, "//td/a/div");
    }

    public List<String> getRow(int rowNumber, String xpath) {
        return getRows().get(rowNumber).findElements(By.xpath(xpath)).stream()
                .map(WebElement::getText).collect(Collectors.toList());
    }
`

2021-01-19 01:35 UTC, OxanaE commented on src/test/java/EntityDefaultTest.java
> +
Refactored to use assert of equal types where it's possible. There's still one test that needs refactoring later.

2021-01-19 01:55 UTC, OxanaE commented
One of the tests (the first one) uses a DefaultViewPage pom which is not ready yet. I'm waiting for someone more knowledgeable to do it. This is the reason I didn't refactor this test yet.

2021-01-20 01:55 UTC, GalinaRuban approved these changes

2021-01-20 07:23 UTC, SergeiDemyanenko approved these changes

2021-01-21 08:05 UTC, Stan575 approved these changes

2021-01-21 22:17 UTC, merged