Refactored
SergeiDemyanenko/PlatformaticaQA pull request #499
Opened 2021-01-20 02:58 UTC by BELOVEZHIE

https://trello.com/c/wKmzv7CC/250-entity-chevron-inputcopy

2021-01-20 05:34 UTC, Stan575 requested changes

2021-01-20 05:34 UTC, Stan575 commented on src/test/java/EntityChevronTest.java
> +        Assert.assertEquals(CHECKING_SIGN, recheckFulfillment.getText());
switch actual and expected parameters : 
    public static void assertEquals(String actual, String expected)

2021-01-20 05:34 UTC, Stan575 commented on src/test/java/EntityChevronTest.java
delete empty lines

2021-01-20 05:34 UTC, Stan575 commented on src/test/java/EntityChevronTest.java
> +                CHECKING_SIGN);
can be one line

2021-01-20 05:34 UTC, Stan575 commented on src/test/java/EntityChevronTest.java
> +    private final String CHECKING_SIGN = "Fulfillment";
should be : private static final

2021-03-07 01:15 UTC, guram21 commented
This PR is no longer relevant

2021-03-07 01:15 UTC, closed without merging