Refactoring of doImportButton and customImportButton tests
SergeiDemyanenko/PlatformaticaQA pull request #506
Opened 2021-01-21 03:08 UTC by DennorQA

2021-01-21 08:51 UTC, Stan575 approved these changes

2021-01-21 08:53 UTC, Stan575 commented
Please add Trello card task to PR description

2021-01-22 18:20 UTC, ke-de-ve requested changes
move By where it is possible to the start of the class as private fields. When it is impossible move xpath instead.

for example:

`private static final By BY_IMPORT_ENTITY = By.xpath("//a[@href='index.php?action=action_list&entity_id=17']"); `

then line 50 would look like:

`WebElement ImportEntity = driver.findElement(BY_IMPORT_ENTITY);`

2021-01-29 23:58 UTC, Stan575 commented
Closed as predecessor of [Refactoring, added BY fields #519](https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/519)

2021-01-29 23:58 UTC, closed without merging