https://trello.com/c/L4P82XPO/486-entity-chevron-inputcopy-2
SergeiDemyanenko/PlatformaticaQA pull request #507
Opened 2021-01-21 04:34 UTC by Marina-sukhova

2021-01-21 05:01 UTC, BELOVEZHIE approved these changes

2021-01-21 07:58 UTC, Stan575 requested changes

2021-01-21 07:58 UTC, Stan575 commented on src/test/java/EntityChevronTest.java
> +        List<WebElement> listOfValues = getDriver().findElements(By.xpath("//tbody//tr[1]//td"));
POM means all selenium code should be moved from tests to pages, in other words all direct interactions with browser/elements are not allowed here

2021-01-21 07:58 UTC, Stan575 commented on src/test/java/EntityChevronTest.java
> +            Assert.assertEquals(getDriver().findElement(By.xpath("//div[contains(text(), 'Fulfillment')]")).getText(), expectedStatus);
same here

2021-01-21 07:58 UTC, Stan575 commented on src/test/java/EntityChevronTest.java
> +            Assert.assertEquals(getDriver().findElement(By.xpath("//div[contains(text(), 'Fulfillment')]")).getText(), expectedStatus);
should second assertion be inside the loop?

2021-01-23 17:45 UTC, Stan575 approved these changes

2021-01-23 22:51 UTC, merged