Refactoring, added BY fields
SergeiDemyanenko/PlatformaticaQA pull request #519
Opened 2021-01-22 23:00 UTC by DennorQA

Accidently have deleted my previous branch "Denys-Branch" for PR https://github.com/SergeiDemyanenko/PlatformaticaQA/pull/506
So I've created new branch and new PR
link for task https://trello.com/c/IYZH9ITy/249-entity-import-input-new-record

2021-01-22 23:17 UTC, Stan575 approved these changes

2021-01-23 18:35 UTC, ke-de-ve approved these changes
Looks overall OK with some areas for improvement around xpath hardcoded in the method(s). In the future it may help to do ignore as a separate PR, then less risk your would be out of sync with main

2021-01-24 00:14 UTC, GalinaRuban approved these changes

2021-01-24 01:04 UTC, Stan575 requested changes
Good job
src/test/java/EntityPlatformFunctions1Test.java and src/test/java/EntityPlatformFunctions2Test.java need to be removed from  PR, you can simply merge from main

2021-01-25 19:19 UTC, Stan575 approved these changes

2021-01-25 19:50 UTC, merged