POM for newCalendar() (only first test)
SergeiDemyanenko/PlatformaticaQA pull request #521
Opened 2021-01-23 02:51 UTC by SVar25

https://trello.com/c/y3tt7UKK/509-entities-calendar-input-pom-implementation

2021-01-23 18:27 UTC, Stan575 requested changes
check the comments, the rest well done

2021-01-23 18:27 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
> +        CalendarEditPage calendarEditPage = mainPage.clickMenuCalendar().clickNewButton();
can be one line

2021-01-23 18:27 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
>          dateTimeElement.click();
selenium code is not allowed here, should be in a page class

2021-01-23 18:27 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
>          listElement.click();
same thing about selenium code

2021-01-23 18:27 UTC, Stan575 commented on src/test/java/EntityCalendarTest.java
> +        //Assert.assertTrue(getDriver().findElement(By.xpath("//tr[@data-index='0']//i[contains(@class, 'fa fa-check-square-o')]")).isDisplayed());
we have strict rules about commented out code

2021-01-23 18:49 UTC, SVar25 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
pre
	{mso-style-priority:99;
	mso-style-link:"HTML Preformatted Char";
	margin:0in;
	font-size:10.0pt;
	font-family:"Courier New";}
span.HTMLPreformattedChar
	{mso-style-name:"HTML Preformatted Char";
	mso-style-priority:99;
	mso-style-link:"HTML Preformatted";
	font-family:"Courier New";}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->  Sent from Mail for Windows 10 From: Stan AretinskiySent: Saturday, January 23, 2021 12:27 PMTo: SergeiDemyanenko/PlatformaticaQACc: Svitlana Varakuta; AuthorSubject: Re: [SergeiDemyanenko/PlatformaticaQA] POM for newCalendar() (only first test) (#521) @Stan575 requested changes on this pull request.check the comments, the rest well doneIn src/test/java/EntityCalendarTest.java:> +        MainPage mainPage = new MainPage(getDriver());+        CalendarEditPage calendarEditPage = mainPage.clickMenuCalendar().clickNewButton();can be one lineI will fix itIn src/test/java/EntityCalendarTest.java:> +        WebElement dateTimeElement = getDriver().findElement(By.xpath("//input[contains(@name, 'datetime')]"));+        dateTimeElement.click();         dateTimeElement.click();selenium code is not allowed here, should be in a page classI cant do it because the datetime element in the calendar is only populated with .click or Action.  I tried many times by analogy with data, but always the test failed. In src/test/java/EntityCalendarTest.java:>          WebElement listElement =                 getWebDriverWait().until(ExpectedConditions.elementToBeClickable(By.xpath("//div[2]/div[1]//div[1]/div/ul/li[2]/a")));         listElement.click();same thing about selenium codeI will fix it In src/test/java/EntityCalendarTest.java:>           WebElement listElement =                 getWebDriverWait().until(ExpectedConditions.elementToBeClickable(By.xpath("//div[2]/div[1]//div[1]/div/ul/li[2]/a")));         listElement.click(); -        driver.findElement(By.xpath("//div[contains(text(), '" + STRING + "')]"));+        Assert.assertTrue(getDriver().findElement(By.xpath("//div[contains(text(), '" + STRING + "')]")).isDisplayed());+        //Assert.assertTrue(getDriver().findElement(By.xpath("//tr[@data-index='0']//i[contains(@class, 'fa fa-check-square-o')]")).isDisplayed());we have strict rules about commented out codeI will fix it —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2021-01-26 00:14 UTC, Stan575 commented
@SVar25 should this PR be closed?

2021-01-26 04:33 UTC, Seid31 approved these changes

2021-01-26 22:22 UTC, closed without merging