EntityChildTest. Improve code.
SergeiDemyanenko/PlatformaticaQA pull request #565
Opened 2021-02-01 20:09 UTC by SVar25

https://trello.com/c/LJSnzttw/540-entity-parent-inputchild-at
https://trello.com/c/ru57VLXh/541-entity-parent-child-edit-at
https://trello.com/c/KNBqvsYO/542-entity-parent-child-delete-at

2021-02-01 21:47 UTC, Stan575 requested changes
overall good job

- would be better if you use less JavaScript click ( ProjectUtils.click(driver, yourElement) )
- please don't create new PR for changes, just push new commit(s) to existing one

2021-02-01 21:47 UTC, Stan575 commented on src/test/java/test/entity/EntityChildTest.java
> +        Assert.assertEquals(resultDate.getText(), DATE);
Asserts aren't necessary if you looking for elements by expected text, same story in editChild test

2021-02-01 21:47 UTC, Stan575 commented on src/test/java/test/entity/EntityChildTest.java
> +    public void deleteChild() {
test has no verification, add appropriate asserts

2021-02-02 03:17 UTC, 4stuntman4 approved these changes

2021-02-02 05:51 UTC, 4stuntman4 approved these changes

2021-02-02 07:27 UTC, Stan575 approved these changes

2021-02-02 10:06 UTC, merged