Footers test branch
SergeiDemyanenko/PlatformaticaQA pull request #567
Opened 2021-02-02 07:25 UTC by KateM-qa

Finished Footers tests, next step to get them to POM refactoring.

2021-02-02 22:22 UTC, Stan575 requested changes
use TestUtils.movingIsFinished for clicking on 'edit' and 'delete' buttons in menu dropdown

2021-02-02 22:22 UTC, Stan575 commented on src/test/java/test/entity/EntityFootersTest.java
> +                () -> driver.findElement(By.xpath("//*[@id='pa-all-entities-table']")));
can be replace with 
`Assert.assertEquals(driver.findElement(By.xpath("//div[contains(@class, 'card-body')]")).getText(), "");`
to avoid 10 second waiting for non existing element

2021-02-04 21:51 UTC, KateM-qa commented on src/test/java/test/entity/EntityFootersTest.java
> +                () -> driver.findElement(By.xpath("//*[@id='pa-all-entities-table']")));
Thank you, made those changes to my test.

2021-02-04 23:23 UTC, panteleyeva approved these changes

2021-02-04 23:27 UTC, Stan575 approved these changes

2021-02-17 18:07 UTC, merged