POM test refactoring
SergeiDemyanenko/PlatformaticaQA pull request #569
Opened 2021-02-02 10:31 UTC by Vadym11

2021-02-02 21:59 UTC, Stan575 requested changes

2021-02-02 21:59 UTC, Stan575 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +    public void PomNewRecordPV(){
test method name should start with lower case letter

2021-02-02 21:59 UTC, Stan575 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +        PlaceholderEdit1Page placeholderEdit1Page = mainPage.clickMenuPlaceholder().clickNewFolder();
can be one line

2021-02-02 21:59 UTC, Stan575 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +        placeholderPage.deleteRow();
this line has no impact

2021-02-03 02:38 UTC, Vadym11 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +        placeholderPage.deleteRow();
I changed it cuz the previous one is written by myself, but since I used EntityBaseTablePage I decided to use already implemented method. At the same time if everything gets reset when we run the whole project (not just one test locally), deleting a record could be skipped.

2021-02-03 02:43 UTC, Vadym11 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +    public void PomNewRecordPV(){
fixed

2021-02-03 02:43 UTC, Vadym11 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +        PlaceholderEdit1Page placeholderEdit1Page = mainPage.clickMenuPlaceholder().clickNewFolder();
I'm not sure what you mean. Can you give me an example of how I can rewrite it into one line?

2021-02-03 03:09 UTC, Stan575 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +        PlaceholderEdit1Page placeholderEdit1Page = mainPage.clickMenuPlaceholder().clickNewFolder();
> I'm not sure what you mean. Can you give me an example of how I can rewrite it into one line?

`        PlaceholderEdit1Page placeholderEdit1Page = new MainPage(driver).clickMenuPlaceholder().clickNewFolder();
`
sorry if it wasn't clear what lines this is about

2021-02-03 04:35 UTC, Stan575 approved these changes

2021-02-03 07:42 UTC, Vadym11 commented on src/test/java/test/entity/EntityPlaceholderInputTest.java
> +        PlaceholderEdit1Page placeholderEdit1Page = mainPage.clickMenuPlaceholder().clickNewFolder();
got it, that makes sense, thanks

2021-02-03 08:30 UTC, 4stuntman4 approved these changes

2021-02-03 08:36 UTC, merged