Fix Board Tests
SergeiDemyanenko/PlatformaticaQA pull request #579
Opened 2021-02-07 01:50 UTC by irina0606

https://trello.com/c/Nfaodd31/315-entityboardtestinputtest

2021-02-07 01:55 UTC, Stan575 requested changes

2021-02-07 01:55 UTC, Stan575 commented on src/test/java/test/entity/EntityBoardTest.java
> +        //dateForValidation = String.format("%1$s%4$s%3$s%4$s%2$s", calendar.getRandomDay() , calendar.getCurrentYear(), calendar.getCurrentMonth(), '-');
commented out code

2021-02-07 01:55 UTC, Stan575 commented on src/test/java/test/entity/EntityBoardTest.java
> +    }*/
commented out code

2021-03-07 01:17 UTC, guram21 commented
This PR is no longer relevant

2021-03-07 01:17 UTC, closed without merging