sa fix EntityFieldsTest
SergeiDemyanenko/PlatformaticaQA pull request #587
Opened 2021-02-08 22:50 UTC by Stan575

[Trello : EntityFieldsTest](https://trello.com/c/w4gbk441/585-entityfieldstest)

2021-02-08 23:22 UTC, Burdishka approved these changes

2021-02-08 23:37 UTC, 4stuntman4 requested changes

2021-02-08 23:37 UTC, 4stuntman4 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
For which reason you need to change it? It should be random value to cover as many numbers as possible. If it is fixed you can not test decimals 123.00. 15. 01 and so on

2021-02-08 23:43 UTC, Stan575 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
in case of random value only one value being  used in all tests cuz original code is:
`private  static final String DECIMAL = Double.toString((int) (Math.random()*20000) / 100.0);`
it's static, so created only once, if you want to test with different values there must be multiple tests with various values
error can be seen here: [https://travis-ci.com/github/SergeiDemyanenko/PlatformaticaQA/builds/216468094](https://travis-ci.com/github/SergeiDemyanenko/PlatformaticaQA/builds/216468094)

2021-02-08 23:46 UTC, 4stuntman4 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
Nope. I disagree. Every time when you start test there will be new value.

2021-02-08 23:49 UTC, 4stuntman4 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
Error means that it still cuts zeros. They did not fix decimal error

2021-02-08 23:51 UTC, Stan575 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
Changed it to fixed value with two zero after decimal point, later in edit test value changed to anther one, so both with and without zero at the end covered

2021-02-08 23:54 UTC, 4stuntman4 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
I disagree just ignore the test untill they fix error with zeros or our test with fixed values will be poor

2021-02-08 23:54 UTC, Stan575 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
> Error means that it still cuts zeros. They did not fix decimal error

application works correct after fix, values like 67.0 converted to 67.00, but test expecting to find 67.0

2021-02-09 00:00 UTC, 4stuntman4 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
It means we need to create random formula that gives us decimals like 67.00 not 67.0. Resolving the issue with hardcoding using fixed values is poor idea

2021-02-09 00:01 UTC, 4stuntman4 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
We can merge your decision untill i fix formula or just ignore it

2021-02-09 00:04 UTC, Stan575 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
both ways would work for me, it's up to you

2021-02-09 00:15 UTC, Stan575 commented on src/test/java/test/entity/EntityBoardTest.java
>      private static final String TEXT_EDIT = "My values are changed";
I don't want to ignore all entity board tests, we can merge this change and you improve tests later, is it ok for you?

2021-02-09 00:18 UTC, 4stuntman4 approved these changes

2021-02-09 00:18 UTC, merged