Denys_branch
SergeiDemyanenko/PlatformaticaQA pull request #646
Opened 2021-03-01 21:23 UTC by DennorQA

https://trello.com/c/TFi87MBt/512-entity-import-input-new-record-automation

added new tests for:

Test Case #3
filteredImport2Button()

Test Case #4
filteredImport3Button()

Test Case #5
selectForEmbededButton()

Test Case #6
selectForEmbededCustomButton()

+ some mininaml refactoring for old tests:
doImportButton()
customImportButton()

2021-03-01 22:02 UTC, Stan575 requested changes
delete unused imports, unnecessary empty lines
add empty line at the end of file

2021-03-01 22:06 UTC, Stan575 commented
@DennorQA please make easy to understand name for PR and put link to Trello task in PR description

2021-03-01 22:07 UTC, DennorQA commented on src/test/java/test/entity/EntityImportTest.java
> +        Thread.sleep(500);
I've tried explicit here, and only Thread.sleep(500); is work here...

2021-03-01 22:20 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +        WebElement clickEmbededBtn = driver.findElement(BY_SELECT_FOR_EMBEDED);
could you name elements in a different way, right here, "clickEmbededBtn" name for "Select For Embeded" button is confusing, hard to read the code

2021-03-01 22:30 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +        Thread.sleep(500);
> I've tried explicit here, and only Thread.sleep(500); is work here...

sleep can be replaced with 
`        getWebDriverWait().until(TestUtils.movingIsFinished(checkbox));
`

2021-03-01 22:35 UTC, Stan575 reviewed
still having extra empty lines, please check the whole file

2021-03-01 22:35 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +
empty line

2021-03-01 22:35 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +
empty line

2021-03-01 22:35 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +
empty line

2021-03-01 22:35 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +
empty line

2021-03-01 22:35 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +
empty line

2021-03-02 00:02 UTC, Stan575 commented on src/test/java/test/entity/EntityImportTest.java
> +        WebElement clickEmbededBtn = driver.findElement(BY_SELECT_FOR_EMBEDED);
why don't you rename web element it to 'selectForEmbededButton' instead of 'clickSelectForEmbeded'?
it would be kind of you to remove 'click' from element names through the class, elements don't do clicks, elements are buttons or text buttons or icons or fields or whatever they are but not clicks

2021-03-02 03:19 UTC, DennorQA commented on src/test/java/test/entity/EntityImportTest.java
> +        WebElement clickEmbededBtn = driver.findElement(BY_SELECT_FOR_EMBEDED);
got it, will do

> why don't you rename web element to 'selectForEmbededButton' instead of 'clickSelectForEmbeded'?
> it would be kind of you to remove 'click' from element names through the class, elements don't do clicks, elements are buttons or text buttons or icons or fields or whatever they are but not clicks

2021-03-02 06:39 UTC, Stan575 approved these changes
In five tests you create WebDriverWait variable that used only once in each test
`WebDriverWait wait = getWebDriverWait();`
from Java perspective it make no sense, getWebDriverWait() is fine to use there

2021-03-02 17:12 UTC, DennorQA commented
Done
> In five tests you create WebDriverWait variable that used only once in each test
> `WebDriverWait wait = getWebDriverWait();`
> from Java perspective it make no sense, getWebDriverWait() is fine to use there
> don't want to put too much pressure on you here, would be nice if you take care of it

2021-03-02 18:03 UTC, GalinaRuban approved these changes

2021-03-02 18:04 UTC, merged