POM for Footer: Edit
SergeiDemyanenko/PlatformaticaQA pull request #679
Opened 2021-03-05 21:49 UTC by Marina-sukhova

2021-03-05 23:03 UTC, Stan575 requested changes

2021-03-05 23:03 UTC, Stan575 commented on src/test/java/model/entity/edit/FootersEditPage.java
> +            WebElement b = pushButtons.get(i);
please do not name variables with a single letter. it's hard to understand the code, in this case 'button' is a appropriate name

2021-03-05 23:10 UTC, homelyn-code reviewed
Waiting a change requested by Stan.

2021-03-05 23:41 UTC, Marina-sukhova commented on src/test/java/model/entity/edit/FootersEditPage.java
> +            WebElement b = pushButtons.get(i);
thanks for paying attention

2021-03-05 23:43 UTC, Stan575 approved these changes

2021-03-06 00:15 UTC, homelyn-code approved these changes

2021-03-07 02:27 UTC, merged