InstallNowTest added.
SergeiDemyanenko/PlatformaticaQA pull request #697
Opened 2021-03-08 18:42 UTC by SVar25

https://trello.com/c/gW3n8gP2/440-portal-marketplace-install-now

2021-03-08 19:32 UTC, guram21 approved these changes

2021-03-08 19:42 UTC, oooleks commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +    private static final String NAME = UUID.randomUUID().toString();;
- use ProjectUtils.createUUID() method instead;
- delete extra semicolon

2021-03-08 19:47 UTC, oooleks commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +        ProjectUtils.click(driver, driver.findElement(INSTALL_NOW));
Try to not use method from ProjectUtils click(WebDriver driver, WebElement element) in every single click as it's Javascipt based but scroll(WebDriver driver, WebElement element) and click(WebDriverWait wait, WebElement element) if element is really out of page visible area.

2021-03-08 19:48 UTC, oooleks commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +        ProjectUtils.click(driver, driver.findElement(INSTALL_NOW));
too many empty lines, try to group the code

2021-03-08 19:49 UTC, oooleks commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +                .visibilityOfElementLocated(By.xpath("//label[@id='_field-note-subdomain']")));
Why wait without any action on the element? You would better to skip it.

2021-03-08 19:51 UTC, oooleks commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +        Assert.assertEquals(resultInst.getText(), "Congratulations! Your instance was successfully created");
Use AppConstant.INSTANCE_CREATED_TEXT instead of the "string"

2021-03-08 19:52 UTC, SVar25 commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +                .visibilityOfElementLocated(By.xpath("//label[@id='_field-note-subdomain']")));
Does not work without this action

2021-03-08 20:46 UTC, Stan575 requested changes

2021-03-08 20:46 UTC, Stan575 commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +    public void installNow() throws InterruptedException {
is there use of Thread.sleep within this test?

2021-03-08 20:46 UTC, Stan575 commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +        getDriver().findElement(BUY_NOW_BTN).click();
variable "driver" already created, why calling getDriver()?

2021-03-08 20:46 UTC, Stan575 commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +        ProjectUtils.click(driver, driver.findElement(RESET_BUTTON));
JavaScript click is fine for resetting the app, but the rest of test should not use it

2021-03-08 20:46 UTC, Stan575 commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +                (By.xpath("//h3[contains(text(),'Congratulations! Your instance was successfully cr')]"));
poor xpath, avoid locators depending on long strings, find another locator

2021-03-08 21:42 UTC, Stan575 requested changes
Don't use JavaScript click from ProjectUtils in test steps.
Add messages to commits that reflect changes, don't use same message over and over!

2021-03-09 00:43 UTC, natxs approved these changes

2021-03-09 17:29 UTC, oooleks commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +        ProjectUtils.click(driver, clickBuyCart);
Will it work without JavaScript click? If no try click(WebDriverWait wait, WebElement element) instead.

2021-03-09 17:29 UTC, oooleks commented on src/test/java/test/portal/MarketplaceMarketplaceTest.java
> +        ProjectUtils.click(driver, driver.findElement(MARKETPLACE));
Will it work without JavaScript click? If no try click(WebDriverWait wait, WebElement element) instead.

2021-03-09 20:33 UTC, Stan575 reviewed
@SVar25 
I still waiting for JavaScript clicks to be replaced

2021-03-09 20:55 UTC, SVar25 commented
I removed JavaScript click. Previously, I could not remove it because my test was not working. And I don't Know why.

2021-03-09 21:24 UTC, Stan575 commented
> I removed JavaScript click. Previously, I could not remove it because my test was not working. And I don't Know why.

`        WebElement simpleCrm = driver.findElement(By.xpath("//a[text()='Simple CRM']"));
        ProjectUtils.click(getWebDriverWait(), simpleCrm);`
would be ok for me, notice that click in code above is not JavaScript click

2021-03-09 23:39 UTC, merged

2021-03-09 23:43 UTC, SVar25 commented
Thanks, Stan. I will do it in the next PR