homework test
SergeiDemyanenko/PlatformaticaQA pull request #70
Opened 2020-12-07 05:30 UTC by olenat2019

2020-12-07 18:46 UTC, natxs commented
Hi, Olena! As for our task, you should name your test with your personal name and place it in the folder (class) which contains  the name of your group

2020-12-07 20:44 UTC, kriuvi requested changes

2020-12-07 20:44 UTC, kriuvi commented on src/test/java/SimpleTest.java
> +    public void descriptionTest()throws InterruptedException{
Название теста должно быть имяФамилия. И добавить его надо было в файл с именем своей группы. Или создать такой файл.

2020-12-07 20:44 UTC, kriuvi commented on src/test/java/SimpleTest.java
> +        WebElement header = driver.findElement(By.xpath("//div//h2[.='About']"));
я думаю, что элемент найдется по xpath = //h2[.='About'] 
То, что он под div - не дает ему никакой уникальности. div значит просто любой контейнер в иерархии выше.

2020-12-09 04:59 UTC, SergeiDemyanenko approved these changes

2020-12-13 18:17 UTC, closed without merging