migrated saveFooter test to POM
SergeiDemyanenko/PlatformaticaQA pull request #723
Opened 2021-03-12 01:28 UTC by KateM-qa

2021-03-12 17:11 UTC, Stan575 requested changes

2021-03-12 17:11 UTC, Stan575 commented on src/test/java/test/entity/EntityFootersTest.java
> +        Assert.assertEquals(fieldsPage.getRow(0,"//tbody/tr/td"), expectedRecordValues);
selenium code (such as direct interactions with web elements, locator usage) is not allowed in pom tests

2021-03-12 17:11 UTC, Stan575 commented on src/test/java/test/entity/EntityFootersTest.java
>          wait.until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.id("pa-all-entities-table")));
selenium code (such as direct interactions with web elements, locator usage) is not allowed in pom tests

2021-03-13 01:05 UTC, Burdishka commented on src/test/java/model/entity/edit/FootersEditPage.java
> +        fill(getWait(), row.findElement(By.cssSelector("td > textarea[id$=text]")), text);
А возможно элементы инициализировать в начале класса и этим сделать тело метода более понятным?

2021-03-13 01:05 UTC, Burdishka commented on src/test/java/test/entity/EntityFootersTest.java
> +                .deleteAllRows()
А зачем удалять все Rows? Перед выполнением тестов разве не выполняется !!! Reset all data !!! ?

2021-03-13 06:07 UTC, KateM-qa commented on src/test/java/test/entity/EntityFootersTest.java
> +                .deleteAllRows()
Так как у нас @Run(run = RunType.Multiple) (есть зависящие друг от друга тесты), то происходит следующее: сначала пробегает тест CreateNewRecord и оставляет после себя запись для использования другими тестами, которые от него зависят. После этого, запускается тест saveFooter, который тоже сохраняет запись, то есть у saveFooter уже две записи (одна его собственная, а другая из CreateNewRecord), а нужна всего одна, поэтому я написала тест deleteAll. Вполне вероятно, что когда все тесты в этом классе будут написаны (а пишут их четыре человека), то мы сделаем рефакторинг, организуем методы и поудалаем лишнее, в том числе и этот тест CreateNewRecord и метод deleteAll. Пока что у нас еще work in progress. Конкретно в этом ПР метод saveFooter переписан в ПОМ.

2021-03-13 07:16 UTC, KateM-qa commented on src/test/java/test/entity/EntityFootersTest.java
> +        Assert.assertEquals(fieldsPage.getRow(0,"//tbody/tr/td"), expectedRecordValues);
Fixed it, created separate method in FootersPage class 
    @Override
    public List<String> getRow(int rowNumber) {
        return getRows().get(rowNumber).findElements(By.tagName("td")).stream()
                .map(WebElement::getText).collect(Collectors.toList());
    }

2021-03-13 07:18 UTC, KateM-qa commented on src/test/java/test/entity/EntityFootersTest.java
>          wait.until(ExpectedConditions.visibilityOfAllElementsLocatedBy(By.id("pa-all-entities-table")));
Fixed this, created a separate method on FootersEditPage
    public FootersEditPage waitVisibilityOfTable() {
        getWait().until(d -> savedTable.isDisplayed());
        return this;
    }

2021-03-13 07:18 UTC, KateM-qa commented on src/test/java/model/entity/edit/FootersEditPage.java
> +    private List<WebElement> maxFtrsRows;
Renamed Ftrs to Footers everywhere

2021-03-13 07:19 UTC, KateM-qa commented on src/test/java/model/entity/edit/FootersEditPage.java
> +        WebDriver driver = getDriver();
Тут драйвер не инициализируется каждый раз в вызове getDriver, а используется драйвер, который передали в page в ее конструкторе.

2021-03-13 07:19 UTC, KateM-qa commented on src/test/java/model/entity/edit/FootersEditPage.java
> +        fill(getWait(), row.findElement(By.cssSelector("td > textarea[id$=text]")), text);
Fixed this.

2021-03-14 04:54 UTC, Stan575 approved these changes

2021-03-14 05:20 UTC, homelyn-code approved these changes

2021-03-14 05:20 UTC, merged