677 Added EntityExportView POM
SergeiDemyanenko/PlatformaticaQA pull request #734
Opened 2021-03-14 07:13 UTC by OGoncharenko

https://trello.com/c/SbG1nO8H/677-entity-export-view-pom

2021-03-14 16:04 UTC, oooleks requested changes

2021-03-14 16:04 UTC, oooleks commented on src/test/java/model/entity/view/ExportViewPage.java
> +public final class ExportViewPage extends EntityBaseViewPage {
No `final `needed

2021-03-14 16:04 UTC, oooleks commented on src/test/java/model/entity/view/ExportViewPage.java
> +    @FindBy(xpath = "//label[text()='String']/../div[5]//span")
No need to to add these elements into view page as these already been covered in `EntityBaseViewPage` like 
`    @FindBy (css = ".pa-view-field")
    private List<WebElement> labeledValues;

    @FindBy (xpath = "//div[@class='form-group']/p")
    private WebElement user;

    @FindBy (xpath = "//table//td")
    private List<WebElement> labeledEmbedValues;`

2021-03-15 21:20 UTC, oooleks approved these changes

2021-03-15 22:55 UTC, guram21 approved these changes

2021-03-16 02:06 UTC, merged