Added autoFillOutForm in EntityBaseEditExtPage. That method works for…
SergeiDemyanenko/PlatformaticaQA pull request #770
Opened 2021-03-20 01:18 UTC by homelyn-code

… new and edit Entities.

2021-03-20 16:20 UTC, oooleks commented on src/test/java/runner/ProjectUtils.java
> +    }
Why hardcode length = 10 if we have already randomString(int stringLength) and createUUID()

2021-03-21 01:42 UTC, homelyn-code commented on src/test/java/runner/ProjectUtils.java
> +    }
для удобства

2021-03-21 01:59 UTC, oooleks commented on src/test/java/runner/ProjectUtils.java
> +    }
so how user will now from its name that it's limited to 10 only, or rename it to randomTenSizeString or use randomString(10)

2021-03-23 00:23 UTC, homelyn-code commented on src/test/java/runner/ProjectUtils.java
> +    }
We have both methods, without params and with params

2021-03-23 00:29 UTC, oooleks commented on src/test/java/runner/ProjectUtils.java
> +    }
We've got already 3 methods to return random String: createUUID(); randomString(int stringLength) and getAlphanumeric(int count). So do you think we need one more with hardcoded length 10?

2021-03-23 00:34 UTC, oooleks requested changes

2021-03-23 00:34 UTC, oooleks commented on src/test/java/model/entity/edit/ExportEditPage.java
> +//    }
delete commented code

2021-03-23 00:34 UTC, homelyn-code commented on src/test/java/runner/ProjectUtils.java
> +    }
Yep, we can remove createUUID()

2021-03-23 03:36 UTC, oooleks approved these changes

2021-03-23 21:34 UTC, guram21 approved these changes

2021-03-24 17:28 UTC, closed without merging