IZ New methods added to ProjectUtils:
SergeiDemyanenko/PlatformaticaQA pull request #772
Opened 2021-03-21 17:26 UTC by ArinaJur

randomInteger(int min, int max) 
createAlphanumericUUID (int count)

2021-03-21 22:00 UTC, homelyn-code requested changes
We have already all random int, decimal and strings. Why do we need more?

2021-03-21 23:24 UTC, ArinaJur commented
> We have already all random int, decimal and strings. Why do we need more?

2021-03-21 23:27 UTC, oooleks commented on src/test/java/runner/ProjectUtils.java
> +    }
It looks like a duplicate of existed method:  `public static String randomString(int stringLength)`. 
Name methods which return some value with "get". 
UUID is not the same as RandomStringUtils.randomAlphanumeric, so do not use it in its name if `java.util.UUID` method has not been used in it.

2021-03-21 23:38 UTC, ArinaJur commented on src/test/java/runner/ProjectUtils.java
> +    }
It is not a dup, because createUUID().substring(0, stringLength); can create the digit in the first place. I need the letter in the first place (my entities start to calculate the values if UUID starting with number). Stan found randomAlphanumeric, which guaranteed the letter in the first place.  My tests always worked with randomAlphanumeric, but I generated them locally. I can continue to generate them locally if needed.

I will rename the method with get.

2021-03-22 01:39 UTC, oooleks approved these changes

2021-03-22 01:40 UTC, guram21 approved these changes

2021-03-22 03:41 UTC, GalinaRuban approved these changes

2021-03-22 03:56 UTC, homelyn-code approved these changes

2021-03-22 03:58 UTC, merged