Entity parent child pom
SergeiDemyanenko/PlatformaticaQA pull request #794
Opened 2021-03-26 03:31 UTC by BogdanQA

https://trello.com/c/cAqKNaYB

Refactoring ParentChildTest 

EntityParentTest
EntityChildTest
EntityParentChildViewTest

Merge all together in POM

2021-03-26 03:32 UTC, guram21 approved these changes

2021-03-26 04:37 UTC, Burdishka approved these changes

2021-03-26 05:29 UTC, MaxBurdin requested changes

2021-03-26 05:29 UTC, MaxBurdin commented on src/test/java/model/entity/view/ParentViewPage.java
> +    private WebElement buttonSave;
These elements belong to edit page. Not view page

2021-03-26 05:29 UTC, MaxBurdin commented on src/test/java/model/entity/view/ParentViewPage.java
>      }
You don't need all these methods here. There are labeledValues element and getValues() method in EntityBaseViewPage that you can use for getting values and verifying in your test.

2021-03-26 05:29 UTC, MaxBurdin commented on src/test/java/test/entity/EntityParentChildTest.java
> +    public void createMultipleParent() {
Each test must include the word Test in its name

2021-03-26 05:29 UTC, MaxBurdin commented on src/test/java/test/entity/EntityParentChildTest.java
> +    public void dragTheRowUp() {
Each test must include the word Test in its name

2021-03-26 05:29 UTC, MaxBurdin commented on src/test/java/test/portal/UserCreationByAdminDraftTest.java
> +    public void newUser() {
Each test must include word Test in its name

2021-03-26 05:29 UTC, MaxBurdin commented on src/test/java/test/portal/UserCreationByAdminDraftTest.java
> +
Empty line. And this test missing assertion

2021-03-26 05:32 UTC, MaxBurdin commented on src/test/java/model/base/BasePage.java
> +import model.entity.edit.ParentEditPage;
This import is unnecessary here

2021-03-26 05:39 UTC, MaxBurdin requested changes

2021-03-26 05:39 UTC, MaxBurdin commented on src/test/java/model/entity/table/ParentTablePage.java
> +    }
You don't need all these methods here. There is getRow() method in EntityBasePage that you can use for getting values and verifying in your test.

2021-03-26 05:50 UTC, MaxBurdin commented on src/test/java/model/base/EntityBaseViewPage.java
> +public class EntityBaseViewPage extends BaseIndexPage {
Why did you decide to inherit from BaseIndexPage?

2021-03-26 16:28 UTC, oooleks commented on src/test/java/model/base/EntityBaseViewPage.java
> +public class EntityBaseViewPage extends BaseIndexPage {
This makes sense to extend from BaseIndexPage as BaseIndexPage contains elements and methods like: getCurrentUser(); resetUserData(); logout() you will not be able to call from view page without such an extension.

2021-03-26 16:33 UTC, oooleks commented on src/test/java/test/portal/UserCreationByAdminDraftTest.java
> +    public void newUser() {
Try to create test name with the template like: **verb** (action on subject ("create", "edit", "view" etc)) + **noun** (subject under test) + word "**Test**"

2021-03-29 21:54 UTC, BogdanQA commented on src/test/java/model/entity/view/ParentViewPage.java
> +    private WebElement buttonSave;
All this methods are for Child menu, which is on Parent view page

2021-03-29 22:05 UTC, BogdanQA commented on src/test/java/test/entity/EntityParentChildTest.java
> +    public void createMultipleParent() {
Fixed

2021-03-29 22:05 UTC, BogdanQA commented on src/test/java/test/entity/EntityParentChildTest.java
> +    public void dragTheRowUp() {
Fixed

2021-03-29 22:42 UTC, BogdanQA commented on src/test/java/test/portal/UserCreationByAdminDraftTest.java
> +    public void newUser() {
This commit here by mistake, Fixed

2021-03-29 22:42 UTC, BogdanQA commented on src/test/java/test/portal/UserCreationByAdminDraftTest.java
> +
This commit here by mistake, Fixed

2021-03-29 22:47 UTC, BogdanQA commented on src/test/java/model/base/BasePage.java
> +import model.entity.edit.ParentEditPage;
Fixed

2021-03-30 03:04 UTC, MaxBurdin commented on src/test/java/model/entity/view/ParentViewPage.java
> +    private WebElement buttonSave;
Do you mean these elements become available when you're adding a child record? Then you need to create a child edit page and inherit it from EntityBaseEditExtPage which has the fields. But what do you need them for anyway? They are not used

2021-04-15 21:29 UTC, oooleks approved these changes

2021-04-16 01:39 UTC, MaxBurdin approved these changes

2021-04-16 01:40 UTC, merged