Refactored EntityGanttTest POM :
SergeiDemyanenko/PlatformaticaQA pull request #799
Opened 2021-03-27 02:50 UTC by guram21

https://trello.com/c/4wpBFByl
- Applied method autoFillOutForm
- Added methods getRowValues, getTitle to EntityBasePage
- Relocated variables NO_RECORDS, RECORD_NOT_DELETED, DRAFT_NOT_DELETED to EntityGanttTest

2021-03-27 03:44 UTC, MaxBurdin requested changes

2021-03-27 03:44 UTC, MaxBurdin commented on src/test/java/model/base/EntityBasePage.java
> +    }
There is getAllRows method in the same class which gets all values of a record. I think we need to keep just one of them.

2021-03-27 03:44 UTC, MaxBurdin commented on src/test/java/test/entity/EntityGanttTest.java
>          final String recordTitle = ganttTablePage.getTitle(0);
Names representing constants (final variables) must be all uppercase using underscore to separate words

2021-03-27 03:44 UTC, MaxBurdin commented on src/test/java/test/entity/EntityGanttTest.java
>          final String entityTitle = ganttTablePage.getTitle(0);
Names representing constants (final variables) must be all uppercase using underscore to separate words

2021-03-27 04:31 UTC, oooleks commented on src/test/java/model/base/EntityBasePage.java
> +    }
Yes, we've got `List<String> getRow(int rowNumber) `method but it does not collect User value and does not skip empty values like this one. Let's Guram confirm

2021-03-27 04:53 UTC, guram21 commented on src/test/java/model/base/EntityBasePage.java
> +    }
As we agreed with Max, going to use his method:
```
    @FindBy (xpath = "//td[9]")
    private WebElement user;

public List<String> getAllRows(int rowNumber) {
    List<String> lst = getRow(rowNumber, "//td/a");
    lst.add(user.getText());
    return lst;
}
```

2021-03-27 04:56 UTC, oooleks approved these changes

2021-03-27 05:27 UTC, MaxBurdin approved these changes

2021-03-29 01:02 UTC, GalinaRuban approved these changes

2021-03-29 05:06 UTC, merged