Ms  localization test
SergeiDemyanenko/PlatformaticaQA pull request #806
Opened 2021-03-29 20:53 UTC by Marina-sukhova

https://trello.com/c/CMqy9kzO/827-localizationby-admin-enabling-the-translation

2021-03-29 21:06 UTC, guram21 approved these changes

2021-03-30 00:04 UTC, BogdanQA approved these changes

2021-03-30 01:01 UTC, GalinaRuban approved these changes

2021-03-30 02:43 UTC, MaxBurdin requested changes

2021-03-30 02:43 UTC, MaxBurdin commented on src/test/java/test/admin/AdminLocalizationTest.java
> +    public void addLanguage() {
each test must include "Test" in it's name

2021-03-30 02:43 UTC, MaxBurdin commented on src/test/java/test/admin/AdminLocalizationTest.java
> +    public void checkTranslation() {
each test must include "Test" in it's name

2021-03-30 02:43 UTC, MaxBurdin commented on src/test/java/test/admin/AdminLocalizationTest.java
> +                .selectLanguage("Arabic");
Verification is missing

2021-03-30 02:43 UTC, MaxBurdin commented on src/test/java/test/admin/AdminLocalizationTest.java
> +                .clickConfigEntity(entityName);
Verification is missing

2021-03-30 02:43 UTC, MaxBurdin commented on src/test/java/test/admin/AdminLocalizationTest.java
> +
Unnecessary blank line

2021-03-30 02:43 UTC, MaxBurdin commented on src/test/java/model/admin/ConfigurationPage.java
> +
Unnecessary blank line

2021-03-31 02:50 UTC, Marina-sukhova commented on src/test/java/test/admin/AdminLocalizationTest.java
> +    public void addLanguage() {
fixed it. thanks

2021-04-02 16:54 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +        String translated = "";
No need in this variable - just return a value based on condition matched.

2021-04-02 16:54 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +            }
Include return in there directly like: `return ddElement.getText();` instead of break, so no variable needed and cycle will be stopped.

2021-04-02 16:54 UTC, oooleks commented on src/test/java/model/admin/AdminLocalizationPage.java
> +        WebElement elementlist = getDriver().findElement(By.xpath("//*[text()[contains(.,'" + newLanguage + "')]]"));
Use `String.format` for string concatenation

2021-04-02 16:54 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +    @FindBy(xpath = "//li//p[contains(text(), 'Entities')]")
Is there a problem with finding an element using P tag? In the project we look for similar items in the main menu by p tag only

2021-04-02 16:54 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +    @FindBy(xpath = "//li//p[contains(text(), 'Constants')]")
Is there a problem with finding an element using P tag? In the project we look for similar items in the main menu by p tag only

2021-04-02 16:54 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +        } return translated;
change to `return "";` in this case.

2021-04-02 18:19 UTC, Marina-sukhova commented on src/test/java/test/admin/AdminLocalizationTest.java
> +                .clickConfigEntity(entityName);
Verification is added

2021-04-03 02:17 UTC, MaxBurdin commented on src/test/java/model/admin/ConfigurationPage.java
> +    @FindBy(xpath = "//a[@id='navbarDropdownProfile']")
If an element has the id, it's better to search by id. Like this @FindBy(id = "navbarDropdownProfile")

2021-04-03 02:19 UTC, MaxBurdin commented on src/test/java/test/admin/AdminLocalizationTest.java
> +    public void checkTranslationTest() {
why is this test ignored? is there a Trello ticket for it?

2021-04-03 02:19 UTC, MaxBurdin approved these changes

2021-04-03 02:33 UTC, guram21 approved these changes

2021-04-03 02:48 UTC, oooleks commented on src/test/java/test/admin/AdminLocalizationTest.java
> +        fieldsPage.createField("New Text", "string");
Verification should be the last action in test, otherwise how to check this last (line 39) step.

2021-04-03 02:48 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +    public String checkAdminSettings(){
If method returns any value of any type start from "get" in its name

2021-04-03 02:48 UTC, oooleks commented on src/test/java/test/admin/AdminLocalizationTest.java
> +        Assert.assertTrue(adminMenu.equalsIgnoreCase(successfulTranslated));
Could be written without one-time use variable like:
`Assert.assertTrue(new ConfigurationPage(getDriver()).checkAdminSettings()
 .equalsIgnoreCase(successfulTranslated));`

2021-04-04 00:50 UTC, oooleks commented on src/test/java/model/admin/AdminLocalizationPage.java
> +        TestUtils.click(getDriver(), languagesButton);
You are using here (33, 34) JavaScript click, which we use in exceptional cases as this click doesn't represent real user action on UI. Use click(WebDriverWait wait, WebElement element) or simple Selenium click() instead.

2021-04-04 00:50 UTC, oooleks commented on src/test/java/model/admin/AdminLocalizationPage.java
> +                TestUtils.click(getDriver(), buttonADD);
Do not use JavaScript click (40) when possible

2021-04-04 00:50 UTC, oooleks commented on src/test/java/model/admin/AdminLocalizationPage.java
> +            if (findLanguage.getText().equalsIgnoreCase(newLanguage)) {
What will happen when "if" statement will never be True? So no return will be possible, hence it will be exception. You may include:
`else {
                throw new RuntimeException(newLanguage+ " is not listed");
            }`
When there is such `else`, you should include `return` into if {} sequence and break no needed.

2021-04-04 00:50 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +import test.admin.AdminSettingsUserInterfaceTest;
Why this import is here? (9)

2021-04-04 00:50 UTC, oooleks commented on src/test/java/test/admin/AdminSettingsUserInterfaceTest.java
> +    private final  String TypeValue = "string";
Use cAmEl case for variable names

2021-04-04 00:50 UTC, oooleks commented on src/test/java/model/admin/ConfigurationPage.java
> +    WebElement adminButton;
We have this element already defined in `BaseIndexPage `file as `userProfileButton` so use it instead.

2021-04-06 23:18 UTC, merged