Footers refactoring
SergeiDemyanenko/PlatformaticaQA pull request #827
Opened 2021-04-04 05:24 UTC by KateM-qa

1. Invoked autoFillOutForm method for sumFooterTest, minFootersTest, averageFooterTest and saveFooterTest

2. Implemented methods getSumValueString, getMinValueString, getAverageValueString which do calculations based on current random generated values (not hardcoded) and compare them with the form values to make sure they match.

3. Organized FootersEditPage - removed unused methods/variables

4. There are still a few tests written by other people and not using methods described above. I will ask them if they want to refactor after/if my changes will be accepted by reviewers and merged.

2021-04-04 17:02 UTC, oooleks requested changes

2021-04-04 17:02 UTC, oooleks commented on src/test/resources/local.properties.TEMPLATE
> +default.password=UNWDnZkJ9O
You are not suppose to edit this template file - please revert

2021-04-04 17:02 UTC, oooleks commented on src/test/resources/local.properties.TEMPLATE
> +marketplace.password=VwmAAQWCEf
You are not suppose to edit this template file - please revert

2021-04-04 17:46 UTC, KateM-qa commented on src/test/resources/local.properties.TEMPLATE
> +default.password=UNWDnZkJ9O
Sorry, reverted

2021-04-04 17:47 UTC, KateM-qa commented on src/test/resources/local.properties.TEMPLATE
> +marketplace.password=VwmAAQWCEf
Reverted

2021-04-04 17:48 UTC, oooleks approved these changes

2021-04-06 00:04 UTC, guram21 approved these changes

2021-04-06 02:47 UTC, Burdishka approved these changes

2021-04-06 02:51 UTC, merged