Refactoring  admin lists calendar view Test to POM
SergeiDemyanenko/PlatformaticaQA pull request #829
Opened 2021-04-05 03:34 UTC by disel20

create new Page, methods, etc

2021-04-05 05:20 UTC, oooleks requested changes

2021-04-05 05:20 UTC, oooleks commented on src/test/java/model/admin/AdminListsConfigPage.java
> +
This element is already present in inherited `ConfigurationPage`, hence delete it from this page.

2021-04-05 05:20 UTC, oooleks commented on src/test/java/model/admin/AdminListsConfigPage.java
> +    }
goHomePage() from ConfigurationPage works well for every Admin config page, so use it instead and delete it from here.

2021-04-06 19:18 UTC, guram21 approved these changes

2021-04-22 03:11 UTC, disel20 commented on src/test/java/model/admin/AdminListsConfigPage.java
> +
Done

2021-04-22 03:11 UTC, disel20 commented on src/test/java/model/admin/AdminListsConfigPage.java
> +    }
Done

2021-04-22 04:50 UTC, oooleks commented on src/test/java/model/admin/configuration/entities/AdminFieldsCalendarPanelPage.java
> +public class AdminFieldsCalendarPanelPage extends AdminListsMainPage {
To be consistent with existed Admin page files I'd name it like "AdminListsCalendarPage" since we've got the same level pages like: AdminListsBoardPage, AdminListsChevronPage, etc.

2021-04-22 04:50 UTC, oooleks commented on src/test/java/test/admin/AdminEntityManagementCalendarTest.java
>          Assert.assertEquals(resultDate.getText(), DATE);
Why the test is not finished reformatting to POM?

2021-04-25 03:59 UTC, disel20 commented on src/test/java/model/admin/configuration/entities/AdminFieldsCalendarPanelPage.java
> +public class AdminFieldsCalendarPanelPage extends AdminListsMainPage {
Done

2021-04-25 04:00 UTC, disel20 commented on src/test/java/test/admin/AdminEntityManagementCalendarTest.java
>          Assert.assertEquals(resultDate.getText(), DATE);
Done

2021-04-29 02:50 UTC, oooleks approved these changes

2021-04-29 02:51 UTC, guram21 approved these changes

2021-05-02 17:07 UTC, Burdishka approved these changes

2021-05-02 17:07 UTC, Burdishka commented on src/test/java/model/admin/configuration/entities/AdminEntitiesCalendarPage.java
> +    }
Конструктор должен находиться сразу после переменных и уже после него находятся методы

2021-05-02 17:07 UTC, Burdishka commented on src/test/java/model/admin/configuration/entities/AdminListsCalendarPage.java
> +    }
Конструктор должен находиться сразу после переменных и уже после него находятся методы

2021-05-02 17:07 UTC, Burdishka commented on src/test/java/model/admin/configuration/entities/AdminListsMainPage.java
>          TestUtils.click(getWait(), saveButton);
уже появился метод TestUtils.scrollAndClick(WebDriver driver, WebDriverWait wait, WebElement element). Можно заменить две строчки этим методом

2021-05-04 01:05 UTC, merged

2021-05-04 02:59 UTC, disel20 commented on src/test/java/model/admin/configuration/entities/AdminEntitiesCalendarPage.java
> +    }
done

2021-05-04 02:59 UTC, disel20 commented on src/test/java/model/admin/configuration/entities/AdminListsCalendarPage.java
> +    }
done

2021-05-04 02:59 UTC, disel20 commented on src/test/java/model/admin/configuration/entities/AdminListsMainPage.java
>          TestUtils.click(getWait(), saveButton);
done