Vt admin chevron filter
SergeiDemyanenko/PlatformaticaQA pull request #831
Opened 2021-04-05 08:00 UTC by Vadym11

https://trello.com/c/c7uh0eKc/771-entity-management-by-admin-chevronfiltering-capability-for-existing-entries

2021-04-05 15:02 UTC, oooleks requested changes

2021-04-05 15:02 UTC, oooleks commented on src/test/java/model/entity/table/ChevronTablePage.java
> -public final class ChevronTablePage extends EntityBaseTablePage<ChevronTablePage, ChevronEditPage, ChevronViewPage> {
Revert this change back

2021-04-06 03:37 UTC, guram21 approved these changes

2021-04-08 20:23 UTC, Vadym11 commented on src/test/java/model/admin/FieldsPage.java
> +            this.createField(String.valueOf(elem), elem.toLowerCase());
new method added in the new version of the PR

2021-04-08 23:32 UTC, oooleks approved these changes

2021-04-08 23:33 UTC, merged