AdminPermissionsEntitiesTest added
SergeiDemyanenko/PlatformaticaQA pull request #836
Opened 2021-04-06 11:20 UTC by SVar25

https://trello.com/c/BFtqiOT0/837-admin-permission-settings-for-users-entity-fields

2021-04-06 18:27 UTC, oooleks requested changes

2021-04-06 18:27 UTC, oooleks commented on src/test/java/model/admin/AdminPermissionsFieldsPage.java
> +        if (personaEditCheckbox.isSelected() || emailReportCheckbox.isSelected()
Are verifying at least one of four conditions to be True or all 4 must be True (in that case use && instead of ||)?

2021-04-06 18:27 UTC, oooleks commented on src/test/java/test/admin/AdminPermissionForUsersEntityTest.java
> +@Run(run = RunType.Multiple)
No `Multiple `needed if there is only one test in class. You may add it later when more dependent tests added.

2021-04-06 18:27 UTC, oooleks commented on src/test/java/test/admin/AdminPermissionForUsersEntityTest.java
> +    private static final String PERSONA_NAME = "Manager";
Could be local in test variable and consider random value; If later more tests added with its usage you may replace to class variable.

2021-04-06 18:27 UTC, oooleks commented on src/test/java/test/admin/AdminPermissionForUsersEntityTest.java
> +
Empty line

2021-04-06 18:27 UTC, oooleks commented on src/test/java/model/admin/AdminPermissionsFieldsPage.java
> +
Empty line

2021-04-06 19:04 UTC, guram21 approved these changes

2021-04-06 20:03 UTC, SVar25 commented on src/test/java/model/admin/AdminPermissionsFieldsPage.java
> +        if (personaEditCheckbox.isSelected() || emailReportCheckbox.isSelected()
Thanks, Oleg

2021-04-07 03:46 UTC, oooleks approved these changes

2021-04-07 03:48 UTC, merged