DT_ImportEditTest_POM
SergeiDemyanenko/PlatformaticaQA pull request #845
Opened 2021-04-08 07:02 UTC by 4stuntman4

convert to POM TC1

https://trello.com/c/F57HPbyt/906-importedittest-convert-to-pom

2021-04-08 07:24 UTC, MaxBurdin requested changes

2021-04-08 07:24 UTC, MaxBurdin commented on src/test/java/model/entity/edit/ImportEditPage.java
> +
Don't duplicate these elements here. You can access them from EntityBaseEditExtPage and EntityBaseEditPage

2021-04-08 07:24 UTC, MaxBurdin commented on src/test/java/model/entity/edit/ImportEditPage.java
> +    }
There is autoFillOutForm method in EntityBaseEditExtPage you can use instead

2021-04-08 07:24 UTC, MaxBurdin commented on src/test/java/model/entity/edit/ImportEditPage.java
> +    }
Duplicate. There is clickSaveButton method in EntityBaseEditPage

2021-04-08 07:24 UTC, MaxBurdin commented on src/test/java/model/entity/table/ImportTablePage.java
> +    private List<WebElement> numberOfRecordsPerPage;
Duplicate. "List\<WebElement> trs" in EntityBasePage

2021-04-08 07:34 UTC, 4stuntman4 commented on src/test/java/model/entity/edit/ImportEditPage.java
> +    }
it uses hard code in case when we need to type date and date time. Better way to use motions that simulate user - click calendar choose random date. Typing current date and time is not a good idea as user is able to use future day and past day. We can not cover those situations when we type current date.

2021-04-08 07:39 UTC, 4stuntman4 commented on src/test/java/model/entity/edit/ImportEditPage.java
> +
ogh thank you good to know

2021-04-08 08:00 UTC, 4stuntman4 commented on src/test/java/model/entity/edit/ImportEditPage.java
> +
done

2021-04-08 08:05 UTC, 4stuntman4 commented on src/test/java/model/entity/edit/ImportEditPage.java
> +    }
deleted

2021-04-08 08:09 UTC, 4stuntman4 commented on src/test/java/model/entity/table/ImportTablePage.java
> +    private List<WebElement> numberOfRecordsPerPage;
done

2021-04-08 18:25 UTC, oooleks commented on src/test/java/model/entity/edit/ImportEditPage.java
> +
This element is already present in `EntityBaseEditPage` which is inherited by `ImportEditPage`, so delete it from here.

2021-04-08 19:58 UTC, 4stuntman4 commented on src/test/java/model/entity/edit/ImportEditPage.java
> +
deleted

2021-04-08 22:54 UTC, guram21 approved these changes

2021-04-08 23:35 UTC, ArinaJur approved these changes

2021-04-09 00:10 UTC, MaxBurdin approved these changes

2021-04-09 01:31 UTC, merged