Localization select all languages
SergeiDemyanenko/PlatformaticaQA pull request #850
Opened 2021-04-09 21:04 UTC by irina0606

https://trello.com/c/gz9Th16M/915-localization-select-all-languages

2021-04-09 21:17 UTC, oooleks requested changes

2021-04-09 21:17 UTC, oooleks commented on src/test/java/model/admin/configuration/translations/AdminUserInterfaceTranslationsPage.java
> +    @FindBy(xpath = "//a[@class='dropdown-item']//span[@class='text']")
It is correct to use the xpath like `"//a[contains(@class,'dropdown-item')]//span[@class='text']"` to find all available languages in the list since we've got one more selected by default element with xpath: `//a[@class='dropdown-item selected active']` which will not be accounted in your way

2021-04-09 21:17 UTC, oooleks commented on src/test/java/model/admin/configuration/translations/AdminUserInterfaceTranslationsPage.java
> +        System.out.println(languagesButton.getText());
Remove them (104, 105)

2021-04-09 21:17 UTC, oooleks commented on src/test/java/model/admin/configuration/translations/AdminUserInterfaceTranslationsPage.java
> +        int count = getAllListedLanguages().size();
Not in use `count` variable

2021-04-09 21:17 UTC, oooleks commented on src/test/java/model/admin/configuration/translations/AdminUserInterfaceTranslationsPage.java
> +        TestUtils.scroll(getDriver(), languageDropdown);
No need to scroll as `allListedLanguages` will return all element once list is open

2021-04-10 01:05 UTC, guram21 approved these changes

2021-04-12 01:20 UTC, oooleks approved these changes

2021-04-12 20:38 UTC, oooleks approved these changes

2021-04-12 23:23 UTC, merged