Project Coding Convention added to README.md
SergeiDemyanenko/PlatformaticaQA pull request #872
Opened 2021-04-18 07:32 UTC by guram21

https://trello.com/c/pH2QcPOe

2021-04-18 12:38 UTC, Burdishka approved these changes

2021-04-18 14:05 UTC, Vadym11 approved these changes

2021-04-18 15:37 UTC, SergeiDemyanenko approved these changes

2021-04-18 17:14 UTC, ke-de-ve requested changes

2021-04-18 17:14 UTC, ke-de-ve commented on README.md
> +TestBase.java : Class to include all common methods to be used by tests and pages
BaseTest.java  - we have test.entity.BaseTest

2021-04-18 17:14 UTC, ke-de-ve commented on README.md
> +The class name should be a noun. Try to make the name simple and descriptive.
Name of the test class should include Test at the end. Name of the page class should include Page at the end.

2021-04-18 17:14 UTC, ke-de-ve commented on README.md
> +Method name should be a verb.
Method name should start with a verb  (do, is, make, change, etc).

2021-04-18 17:14 UTC, ke-de-ve commented on README.md
> +The variable name should be a noun. Try to make the name simple and descriptive.
Try to make the name simple and descriptive using full words (button and not btn).

2021-04-18 18:27 UTC, ke-de-ve approved these changes

2021-04-18 23:29 UTC, MaxBurdin requested changes

2021-04-18 23:29 UTC, MaxBurdin commented on README.md
> +Constants (final variables) must be all upper Snake cases, stylized as `SNAKE_CASE`.<br>
Constants are final **static** variables
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html

2021-04-19 01:10 UTC, GalinaRuban approved these changes

2021-04-19 01:20 UTC, MaxBurdin commented on README.md
> +rundomUser
r**a**ndomUser?

2021-04-19 01:20 UTC, MaxBurdin approved these changes

2021-04-19 05:36 UTC, merged