Sv  admin menu management test
SergeiDemyanenko/PlatformaticaQA pull request #879
Opened 2021-04-19 22:16 UTC by SVar25

https://trello.com/c/qyznacbA/936-menu-management-by-admin-entities
without additional assertions (can be done as separate tests)

2021-04-19 23:23 UTC, oooleks requested changes

2021-04-19 23:23 UTC, oooleks commented on src/test/java/model/admin/configuration/menu/AdminMainMenuConfigPage.java
> +    private WebElement projectCheckbox;
Do not name UI elements like test data ("Project", "Clients"). These are Entity check-boxes. It would be better to define xpath "//div[@id='entities']//label" that finds all such elements in the page as a List of Web Elements.

2021-04-19 23:23 UTC, oooleks commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +                .clickManagementMenu()
No need to go around as you stay at the same page after Add button clicked.

2021-04-19 23:23 UTC, oooleks commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +        Assert.assertEquals(new ConfigurationPage(getDriver())
Is any validation for user UI changes planned?

2021-04-19 23:23 UTC, oooleks commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +        String entityName2 = TestUtils.createUUID();
Only one entity is sufficient for Menu Management validation (redundant steps)

2021-04-19 23:23 UTC, oooleks commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +                .getHomeUnderMenuTab(), Home);
The validation is not related to test actions, as you validate the default value of the element which is not changed since test runs.

2021-04-20 00:37 UTC, SVar25 commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +        String entityName2 = TestUtils.createUUID();
Okay. In the US need to have two (Precondition: being logged in as an admin. Have at least two previously created entities.)

2021-04-20 00:38 UTC, SVar25 commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +        Assert.assertEquals(new ConfigurationPage(getDriver())
Yes. This will be in the next PR.

2021-04-20 00:52 UTC, oooleks commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +        String entityName2 = TestUtils.createUUID();
Anyway I do not see any point so far in second entity to validate: "Verify that these entities are now displayed under the Menu tab on the right". Furthermore you can validate changing the order with the default "Home" menu or create second entity for that particular test but not for current one.

2021-04-20 03:12 UTC, SVar25 commented on src/test/java/test/admin/AdminManagementMenuTest.java
> +        String entityName2 = TestUtils.createUUID();
I removed second entity

2021-04-23 23:59 UTC, guram21 approved these changes

2021-04-27 22:54 UTC, oooleks approved these changes

2021-04-28 15:33 UTC, merged