Added test in the Group_lets_do_it.java
SergeiDemyanenko/PlatformaticaQA pull request #96
Opened 2020-12-08 07:38 UTC by 4stuntman4

2020-12-08 18:08 UTC, kriuvi requested changes
Всё хорошо с тестом, можно было бы мерджить, но надо разрешить конфликты.

2020-12-08 18:12 UTC, 4stuntman4 commented
> Всё хорошо с тестом, можно было бы мерджить, но надо разрешить конфликты.

А какие там могут быть конфликты - я только несколько строк добавил в файл. Где вы видите конфликты?

2020-12-10 02:24 UTC, kriuvi requested changes

2020-12-10 02:24 UTC, kriuvi commented on src/test/java/Group_lets_do_it.java
> +
лишняя пустая строка

2020-12-10 02:24 UTC, kriuvi commented on src/test/java/Group_lets_do_it.java
лишняя пустая строка

2020-12-10 02:24 UTC, kriuvi commented on src/test/java/Group_lets_do_it.java
> +        browser.findElement(By.xpath("//li/a[text()='Shop Plans']")).click();
между 42 и 43 пустая строка должна быть

2020-12-10 02:24 UTC, kriuvi commented on src/test/java/Group_lets_do_it.java
> +
44я строка может быть, а можно убрать.

2020-12-10 02:24 UTC, kriuvi commented on src/test/java/Group_lets_do_it.java
> +        browser.findElement(By.xpath("//li/a[text()='Shop Plans']")).click();
По xpath -  на самом деле, //li - абсолютно необязательно, элемент с таким текстом уникальный и так на странице. В некоторых случаях имеет смысл использовать //li[@id='test']/a[....]

Сейчас можно оставить и так, это на будущее

2020-12-10 02:24 UTC, kriuvi commented on src/test/java/Group_lets_do_it.java
> +import org.openqa.selenium.support.ui.Select;
не вижу где ты используешь этот импорт. Он тебе нужен?

2020-12-10 02:42 UTC, kriuvi approved these changes

2020-12-10 03:48 UTC, merged